import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {fresh,ready,put,ref,record,review,readRequest,assumptions,definition} from './support.mjs';
import {resume,readResume} from '../../.agents/skills/kidea/scripts/resume.mjs';
import {byteIntegrity} from '../../.agents/skills/kidea/scripts/bootstrap-plan.mjs';
mkdirSync('.test-output/r09',{recursive:true});
const base=mkdtempSync(path.resolve('.test-output/r09/delivery-'));console.log('Delivery evidence: '+base);
let seq=0;
const files=['docs/source.txt','docs/artifact.txt','docs/config.txt','docs/schema.txt','docs/script.txt','docs/evidence.txt','docs/execute.json','docs/recover.txt'];
function request(root,plan,proposal,reviewId=null,extra=[]) {
 const read=readRequest(root,[...files.map(ref),ref(proposal),...extra]),r=readResume(root,read);
 assert.ok(r.context,JSON.stringify(r));
 return {...read,operation:plan.operation,proposalRef:ref(proposal),reviewId,conditionsMet:true,statement:'Synthetic authorized record only.',expectedBasis:r.basis,expectedProjectId:r.context.projectId,expectedOwnerId:r.context.currentItem.id,expectedGit:r.context.checkout,permission:{...read.permission,allowDeliveryRecord:true,recordPath:plan.recordPath,ownerId:r.context.currentItem.id,statement:'Synthetic selected record authorization.',assumptions}};
}
async function perform(root,plan,extra=[]){const proposal=`docs/proposal-${++seq}.json`;put(root,proposal,JSON.stringify(plan));let id=null;if(plan.operation==='RECORD_RELEASE'){id='release-review-'+seq;await review(root,id,[record(root).currentItemId],[...files.map(ref),ref(proposal)]);}const q=request(root,plan,proposal,id,extra),result=await resume(root,q);assert.equal(result.state,'DELIVERY_RECORDED',JSON.stringify(result));return q;}
async function released(inProgress=false){const root=await (inProgress?ready(base):fresh(base));for(const f of files)put(root,f,f==='docs/execute.json'?JSON.stringify({stepIds:['deploy','readback']}):`Synthetic immutable ${f}\n`);const plan={operation:'RECORD_RELEASE',recordPath:'docs/release.md',nextAction:'Inspect fixture record.',id:'RL1',revision:1,productVersion:'0.1',components:[{id:'web',version:'0.1',sourceRefs:[ref(files[0])],artifactRef:ref(files[1])}],configRefs:[ref(files[2])],schemaRefs:[ref(files[3])],scriptRefs:[ref(files[4])],evidenceRefs:[ref(files[5])],executionPlanRef:ref(files[6]),recoveryPlanRef:ref(files[7])};await perform(root,plan);return {root,plan};}
async function start(root,id='OP1',previousAttemptId=null){return perform(root,{operation:'START_OPERATION',recordPath:`docs/${id}.md`,nextAction:'Read back actual selected target.',id,releasePath:'docs/release.md',releaseId:'RL1',releaseRevision:record(root,'docs/release.md').revision,releaseIntegrity:byteIntegrity(readFileSync(path.join(root,'docs/release.md'))),previousAttemptId,environment:'lab',targetId:'fake-target',actor:'synthetic',startedAt:'2026-09-17T00:00:00.000Z'});}
function receipt(root,id='OP1',result='SUCCEEDED'){const op=record(root,`docs/${id}.md`),release=record(root,'docs/release.md');return {operationId:id,releaseId:op.release.id,releaseRevision:op.release.revision,releaseIntegrity:op.release.recordVersion.integrity,environment:op.environment,targetId:op.targetId,at:'2026-09-17T00:01:00.000Z',scriptIntegrities:release.scriptRefs.map(v=>v.integrity),schemaIntegrities:release.schemaRefs.map(v=>v.integrity),components:[{id:'web',result,artifactRef:result==='SUCCEEDED'?ref(files[1]):null,configRefs:result==='SUCCEEDED'?[ref(files[2])]:[],detail:'Synthetic receipt, not a live deployment.'}],steps:[{id:'readback',result,evidenceRefs:[ref(files[5])],detail:'Synthetic readback fixture.'}]};}
async function observe(root,body,id='obs-1',op='OP1'){const p=`docs/receipt-${++seq}.json`;put(root,p,JSON.stringify(body));return perform(root,{operation:'OBSERVE_OPERATION',recordPath:`docs/${op}.md`,nextAction:'Keep observation history.',observationId:id,receiptRef:ref(p)},[ref(p)]);}

test('public release, UNKNOWN/FAILED history and retry have distinct attempt identity',async()=>{
 const {root}=await released();await start(root);await observe(root,receipt(root,'OP1','UNKNOWN'),'unknown');await observe(root,receipt(root,'OP1','FAILED'),'failed');const before=readFileSync(path.join(root,'docs/OP1.md'));await start(root,'OP2','OP1');await observe(root,receipt(root,'OP2'),'success','OP2');assert.ok(readFileSync(path.join(root,'docs/OP1.md')).equals(before));assert.deepEqual(record(root,'docs/OP1.md').observations.map(o=>o.components[0].result),['UNKNOWN','FAILED']);assert.equal(record(root,'docs/OP2.md').previousAttemptId,'OP1');
});
test('wrong target/revision/script/artifact/config and invented step cannot certify success',async()=>{
 const {root}=await released();await start(root);const before=readFileSync(path.join(root,'docs/OP1.md'));
 for(const mutate of [r=>r.targetId='other',r=>r.releaseRevision++,r=>r.scriptIntegrities=[],r=>r.schemaIntegrities=[],r=>r.components[0].artifactRef=ref(files[0]),r=>r.components[0].configRefs=[],r=>r.steps[0].id='invented']){const r=receipt(root);mutate(r);await assert.rejects(observe(root,r),e=>e.code.startsWith('DELIVERY_READBACK_'));assert.ok(readFileSync(path.join(root,'docs/OP1.md')).equals(before));}
});
test('new release revision retains old attempt pin and refuses stale request or overwritten attempt',async()=>{
 const {root,plan}=await released();const q=await start(root),old=record(root,'docs/OP1.md').release;await perform(root,{...plan,revision:2,productVersion:'0.2'});assert.deepEqual(record(root,'docs/OP1.md').release,old);await assert.rejects(resume(root,q),{code:'DELIVERY_BASIS_CHANGED'});await assert.rejects(start(root),{code:'DELIVERY_ATTEMPT_CREATE_ONLY'});await start(root,'OP2','OP1');assert.equal(record(root,'docs/OP2.md').release.revision,2);
});
test('BUGFIX round pins an actual public release while retaining unfinished MVP work',async()=>{
 const {root}=await released(true),release=record(root,'docs/release.md'),releaseRef={path:'docs/release.md',id:release.id,revision:release.revision,recordVersion:{source:ref('docs/release.md'),location:{kind:'SNAPSHOT',ref:ref('docs/release.md')},integrity:byteIntegrity(readFileSync(path.join(root,'docs/release.md')))}};
 async function cycle(plan){const proposal=`docs/hotfix-${++seq}.json`,id='hotfix-review-'+seq;put(root,proposal,JSON.stringify(plan));await review(root,id,[record(root).currentItemId],[ref(proposal),ref('docs/plan.md'),ref('docs/release.md')]);const b=readRequest(root,[ref(proposal),ref('docs/release.md')]),r=readResume(root,b);return resume(root,{...b,operation:plan.operation,proposalRef:ref(proposal),reviewId:id,conditionsMet:true,statement:'Synthetic reviewed hotfix.',expectedBasis:r.basis,expectedProjectId:r.context.projectId,expectedOwnerId:r.context.currentItem.id,expectedGit:r.context.checkout,permission:{...b.permission,allowWorkCycle:true,ownerId:r.context.currentItem.id,statement:'Synthetic authorized hotfix round.',assumptions}});}
 assert.equal((await cycle({operation:'CREATE_ROUND',reason:'Synthetic defect in pinned release.',nextAction:'Choose hotfix explicitly.',baselineRef:ref('docs/release.md'),round:{id:'FIX',name:'Synthetic hotfix',type:'BUGFIX',scopeRefs:[ref('docs/plan.md')],targetVersion:'0.1.1',releaseRef},items:Array.from({length:10},(_,i)=>({id:`FIX-${i+1}`,roundId:'FIX',name:`Step ${i+1}`,kind:'STEP',parentId:null,shape:'GROUP',decomposition:'UNEXPANDED',...definition,dependencyIds:i?[`FIX-${i}`]:[]}))})).state,'WORK_RECORDED');
 assert.equal((await cycle({operation:'SWITCH_ROUND',reason:'Prioritize hotfix.',nextAction:'Prepare fix.',targetRoundId:'FIX',nextItemId:'FIX-1'})).state,'WORK_RECORDED');const w=record(root);assert.equal(w.items.find(i=>i.id==='A').executionStatus,'IN_PROGRESS');assert.equal(w.returnStack.at(-1).itemId,'A');assert.deepEqual(w.rounds.find(r=>r.id==='FIX').releaseRef,releaseRef);
});
