import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fresh,put,ref,record,review,readRequest,assumptions,definition,work} from './support.mjs';
import {resume,readResume} from '../../.agents/skills/kidea/scripts/resume.mjs';
import {readChange,change} from '../../.agents/skills/kidea/scripts/change.mjs';
import {readStatus} from '../../.agents/skills/kidea/scripts/status.mjs';
import {recordBytes,byteIntegrity} from '../../.agents/skills/kidea/scripts/bootstrap-plan.mjs';
import {resolveGitExecutable} from '../../.agents/skills/kidea/scripts/git-versions.mjs';
mkdirSync('.test-output/r09',{recursive:true});const base=mkdtempSync(path.resolve('.test-output/r09/interop-'));console.log('Interop evidence: '+base);let serial=0;
test('impact CLOSE in CHANGE keeps the paused MVP blocker without treating it as a current impact blocker',async()=>{
 const root=await fresh(base);
 async function cycle(plan){const id='cycle-'+(++serial),p=`docs/${id}.json`;put(root,p,JSON.stringify(plan));await review(root,id,[record(root).currentItemId],[ref(p),ref('docs/plan.md')]);const b=readRequest(root,[ref(p)]),r=readResume(root,b);const out=await resume(root,{...b,operation:plan.operation,proposalRef:ref(p),reviewId:id,conditionsMet:true,statement:'Synthetic approved cycle.',expectedBasis:r.basis,expectedProjectId:r.context.projectId,expectedOwnerId:r.context.currentItem.id,expectedGit:r.context.checkout,permission:{...b.permission,allowWorkCycle:true,ownerId:r.context.currentItem.id,statement:'Synthetic cycle grant.',assumptions}});assert.equal(out.state,'WORK_RECORDED');}
 await cycle({operation:'CREATE_ROUND',reason:'Synthetic change while MVP step1 is blocked.',nextAction:'Choose round.',baselineRef:ref('docs/plan.md'),round:{id:'CHANGE',name:'Change fixture',type:'CHANGE',scopeRefs:[ref('docs/plan.md')],targetVersion:null,releaseRef:null},items:Array.from({length:10},(_,i)=>({id:`C${i+1}`,roundId:'CHANGE',name:`Step ${i+1}`,kind:'STEP',parentId:null,shape:'GROUP',decomposition:'UNEXPANDED',...definition,dependencyIds:i?[`C${i}`]:[]}))});
 await cycle({operation:'SWITCH_ROUND',reason:'Choose change.',nextAction:'Prepare step1.',targetRoundId:'CHANGE',nextItemId:'C1'});
 await work(root,'DECOMPOSE',{definition,children:[{id:'FIX',roundId:'CHANGE',name:'Fix fixture',kind:'TASK',parentId:'C1',shape:'LEAF',decomposition:null,...definition,dependencyIds:[],gateIds:[],resultRefs:[],executionStatus:'TODO'}]});await review(root,'change-step',['C1']);await work(root,'RESOLVE_BLOCKERS',{blockers:record(root).blockers.filter(b=>b.itemId==='C1')});await work(root,'SELECT',{nextItemId:'FIX'});await work(root,'START');
 const b=()=>({operation:'READ',permission:{root,readProject:true,allowReadLocalGit:false,allowImpactWrite:true,roundId:'CHANGE',ownerId:record(root).currentItemId,statement:'Synthetic impact.',assumptions},requiredFiles:[ref('docs/plan.md'),ref('docs/results.md')]});
 async function impact(operation,extra={}){const q={...b(),...extra},r=readChange(root,q);const out=await change(root,{...q,operation,expectedBasis:r.basis,expectedProjectId:r.context.projectId,expectedRoundId:'CHANGE',expectedOwnerId:r.context.currentItem.id,expectedGit:null});assert.equal(out.state,'IMPACT_RECORDED');}
 await impact('OPEN',{graph:{format:'kidea-impact-graph-r1',nodes:[{id:'N',name:'No-diff consumer',...definition}],seeds:['N'],edges:[],diagnostics:[]}});
 let r=readChange(root,b());await impact('ASSESS',{assessment:{nodeId:'N',inputBasis:r.inputBasis,verdict:'NO_CHANGE',reason:'Synthetic source review.',behavior:'Paused MVP remains blocked.',assumptions:'Fixture only.',verification:'Review exact source.',evidenceRefs:[ref('docs/plan.md')],downstream:[],resolved:true}});
 r=readChange(root,b());const owner=r.obligations[0].itemId,item=readStatus(root).data.items.find(i=>i.id===owner);await review(root,'impact-result',[owner],[...new Map([item.scopeRef,item.completionRef,...item.inputRefs,...item.resultRefs].map(r=>[JSON.stringify(r),r])).values()]);
 const blockers=record(root).blockers;assert.ok(blockers.some(b=>b.itemId==='W-001'));await impact('CLOSE',{closure:{conditionsMet:true,semanticStatement:'Close only this change impact.',evidenceRefs:[ref('docs/plan.md')]}});const w=record(root);assert.deepEqual(w.blockers,blockers);assert.equal(w.currentItemId,'FIX');assert.equal(w.returnStack[0].itemId,'W-001');assert.equal(w.items.find(i=>i.id==='FIX').executionStatus,'IN_PROGRESS');
});
test('existing schema2 Git-pinned release and execution-plan evidence can receive a new observation',async()=>{
 const root=await fresh(base),inputs=['docs/source','docs/artifact','docs/config','docs/schema','docs/script','docs/evidence','docs/execute.json','docs/recover'];for(const p of inputs)put(root,p,p.endsWith('.json')?JSON.stringify({stepIds:['readback']}):'Synthetic '+p);
 async function delivery(plan,git=false,extra=[],reviewId=null){const p=`docs/plan-${++serial}.json`;put(root,p,JSON.stringify(plan));if(plan.operation==='RECORD_RELEASE'){reviewId='release';await review(root,reviewId,['W-001'],[ref(p),...inputs.map(ref)]);}const b=readRequest(root,[ref(p),...inputs.map(ref),...extra]);b.permission.allowReadLocalGit=git;const r=readResume(root,b);assert.ok(r.context,JSON.stringify(r));const out=await resume(root,{...b,operation:plan.operation,proposalRef:ref(p),reviewId,conditionsMet:true,statement:'Synthetic delivery record.',expectedBasis:r.basis,expectedProjectId:r.context.projectId,expectedOwnerId:r.context.currentItem.id,expectedGit:r.context.checkout,permission:{...b.permission,allowDeliveryRecord:true,recordPath:plan.recordPath,ownerId:r.context.currentItem.id,statement:'Synthetic selected record grant.',assumptions}});assert.equal(out.state,'DELIVERY_RECORDED',JSON.stringify(out));}
 await delivery({operation:'RECORD_RELEASE',recordPath:'docs/release.md',nextAction:'Record attempt.',id:'RL',revision:1,productVersion:'1',components:[{id:'web',version:'1',sourceRefs:[ref(inputs[0])],artifactRef:ref(inputs[1])}],configRefs:[ref(inputs[2])],schemaRefs:[ref(inputs[3])],scriptRefs:[ref(inputs[4])],evidenceRefs:[ref(inputs[5])],executionPlanRef:ref(inputs[6]),recoveryPlanRef:ref(inputs[7])});
 await delivery({operation:'START_OPERATION',recordPath:'docs/attempt.md',nextAction:'Observe.',id:'OP',releasePath:'docs/release.md',releaseId:'RL',releaseRevision:1,releaseIntegrity:byteIntegrity(readFileSync(path.join(root,'docs/release.md'))),previousAttemptId:null,environment:'lab',targetId:'fake',actor:'synthetic',startedAt:null});
 const git=resolveGitExecutable(root),run=args=>{const r=spawnSync(git,args,{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};run(['init','--initial-branch=master']);run(['config','user.name','Synthetic Fixture']);run(['config','user.email','fixture@example.invalid']);run(['add','.']);run(['commit','-m','Synthetic immutable source fixture']);const first=run(['rev-parse','HEAD']);
 // Pre-existing schema2 compatibility fixture: change only reference location,
 // not product results/approval. Public OBSERVE must read this valid old form.
 const release=record(root,'docs/release.md');release.executionPlanRef.location={kind:'GIT',commit:first,path:inputs[6]};put(root,'docs/release.md',recordBytes(release));run(['add','docs/release.md']);run(['commit','-m','Synthetic Git-pinned release fixture']);const commit=run(['rev-parse','HEAD']),op=record(root,'docs/attempt.md');op.release.recordVersion.location={kind:'GIT',commit,path:'docs/release.md'};op.release.recordVersion.integrity=byteIntegrity(readFileSync(path.join(root,'docs/release.md')));put(root,'docs/attempt.md',recordBytes(op));assert.equal(readStatus(root).readState,'OK');
 const receipt={operationId:'OP',releaseId:'RL',releaseRevision:1,releaseIntegrity:op.release.recordVersion.integrity,environment:'lab',targetId:'fake',at:'2026-09-17T00:00:00.000Z',scriptIntegrities:release.scriptRefs.map(v=>v.integrity),schemaIntegrities:release.schemaRefs.map(v=>v.integrity),components:[{id:'web',result:'SUCCEEDED',artifactRef:ref(inputs[1]),configRefs:[ref(inputs[2])],detail:'Synthetic readback.'}],steps:[{id:'readback',result:'SUCCEEDED',evidenceRefs:[ref(inputs[5])],detail:'Synthetic evidence.'}]};put(root,'docs/receipt.json',JSON.stringify(receipt));await delivery({operation:'OBSERVE_OPERATION',recordPath:'docs/attempt.md',nextAction:'Keep historical observation.',observationId:'OBS',receiptRef:ref('docs/receipt.json')},true,[ref('docs/receipt.json')]);assert.equal(record(root,'docs/attempt.md').observations.length,1);
});
