import assert from 'node:assert/strict';
import {existsSync,readFileSync,writeFileSync,renameSync} from 'node:fs';
import {decodeReceipt} from './control-receipt.mjs';
import {sleep} from './socket-client.mjs';
export async function checkOperations({context,base,record,closeExisting}){
 await closeExisting();const contexts=[],proof={scope:'Real C++ partial M1/M2/M4 + primary W5 over verified TLS; fault DB/lifecycle/HTTP responses explicitly controlled; no full OP/WQ/E1/backup/oncall claim',samples:[],faults:[],permissions:[],requests:[],viewports:[]};
 const make=async(a,options={})=>{const c=await context(a,options);contexts.push(c);return c;};
 let serial=existsSync('/out/control-request.json')?JSON.parse(readFileSync('/out/control-request.json')).id:0;
 async function control(action){const id=++serial,f='/out/operations-control-'+id+'.tmp';writeFileSync(f,JSON.stringify({id,action}));renameSync(f,'/out/control-request.json');for(let i=0;i<100;i++){if(existsSync('/out/control-error.txt'))throw Error(readFileSync('/out/control-error.txt','utf8'));const r='/out/control-result-'+id+'.receipt';if(existsSync(r)){const v=decodeReceipt(readFileSync(r,'utf8'),id,action);if(v){proof.faults.push(v);return v;}}await sleep(100);}throw Error('OPERATIONS_CONTROL_TIMEOUT '+action);}
 const a=await make('A'),b=await make('B'),anon=await make(null),u=await make('U');
 async function metric(c=a,status=200){const r=await c.request.get(base+'/api/v1/admin/operations');assert.equal(r.status(),status);const j=await r.json();if(status===200){assert.equal(r.headers()['cache-control'],'no-store');assert.equal(j.writeReady,false);proof.samples.push(j);}return j;}
 let repaired=false;
 try{
  for(const [c,expected]of [[anon,401],[u,404]]){const j=await metric(c,expected);assert.ok(!JSON.stringify(j).includes('signals'));const r=await c.request.get(base+'/operations');assert.equal(r.status(),expected);const html=await r.text();assert.ok(!html.includes('firstSeenMs')&&!html.includes('lastSuccess'));proof.permissions.push({expected,api:j,ssrStatus:r.status()});}
  const forged=await u.request.get(base+'/api/v1/admin/operations',{headers:{'x-role':'admin','x-actor':'A'}});assert.equal(forged.status(),404);record('operations-anonymous-participant-forged-role-HTTP-SSR-no-private-metrics');
  const command={epoch:'epoch-t02-fixture',intentId:'ops-real-source-create',action:'CREATE',fields:{title:'OPS telemetry authority fixture',description:'FAKE controlled fault fixture only',capacity:10,schedule:{start:'2026-12-10T09:00:00+07:00',end:'2026-12-10T10:00:00+07:00'}}};await sleep(1100);const r=await a.request.post(base+'/api/v1/admin/intents',{headers:{origin:base,'x-csrf-token':'FAKE-CSRF-A'},data:command});assert.equal(r.status(),200);proof.created={command,result:await r.json()};assert.equal(proof.created.result.code,'CREATED');
  let actual;for(let i=0;i<30;i++){actual=await metric();if(actual.signals.M1.pending===0&&actual.signals.M2.state==='KNOWN'&&actual.signals.M4.lastSuccess?.workshop===proof.created.result.workshopId)break;await sleep(250);}assert.equal(actual.signals.M1.pending,0);assert.equal(actual.signals.M1.ageBasis,'EMPTY_NA');assert.equal(actual.signals.M4.lastSuccess.workshop,proof.created.result.workshopId);assert.equal(actual.signals.M4.lastSuccess.version,'1');record('operations-real-durable-writer-processing-source-M1-M4-not-browser-receipt');
  const page=await a.newPage();page.on('request',r=>proof.requests.push({method:r.method(),path:new URL(r.url()).pathname}));const first=await page.goto(base+'/operations');assert.equal(first.status(),200);assert.equal(first.headers()['cache-control'],'no-store');await page.getByRole('heading',{name:'Cập nhật dữ liệu',exact:true}).waitFor();await page.getByText('Không áp dụng — đã xác nhận rỗng',{exact:true}).waitFor();assert.ok((await page.content()).includes('Ngoài phiên thử'));assert.equal(await page.getByRole('button',{name:'Làm mới dữ liệu',exact:true}).count(),1);record('operations-primary-admin-SSR-poll-read-only-explicit-unknowns-outside-run');
  for(const [name,vp,scale]of [['mobile',{width:360,height:780},1],['desktop',{width:1280,height:900},1],['text200',{width:360,height:780},2]]){await page.setViewportSize(vp);await page.addStyleTag({content:'html{font-size:'+16*scale+'px}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Làm mới dữ liệu',exact:true}).focus();assert.equal(await page.getByRole('button',{name:'Làm mới dữ liệu',exact:true}).evaluate(e=>e===document.activeElement),true);await page.screenshot({path:'/out/operations-'+name+'.png',fullPage:true});proof.viewports.push({name,vp,scale,overflow:false,keyboardFocus:true});}record('operations-primary-360-1280-text200-keyboard-no-horizontal-overflow');
  let altered=true;await page.route('**/api/v1/admin/operations',async route=>{if(!altered)return route.continue();const r=await route.fetch();const j=await r.json();j.sampledAtMs-=10000;await route.fulfill({response:r,json:j});});await page.getByText('Không có quan sát mới hợp lệ.',{exact:false}).waitFor();altered=false;await page.getByRole('button',{name:'Làm mới dữ liệu',exact:true}).click();await page.getByText('Không có quan sát mới hợp lệ.',{exact:false}).waitFor({state:'hidden'});await page.unroute('**/api/v1/admin/operations');record('operations-injected-stale-HTTP-sample-does-not-refresh-freshness-real-read-recovers');
  await control('OPS_FAULT_INVARIANT');await page.getByText('Có lỗi nghiêm trọng đã biết',{exact:true}).waitFor();actual=await metric();assert.equal(actual.signals.M2.state,'UNKNOWN');assert.ok(actual.signals.M2.open.some(e=>e.code==='INVARIANT'&&e.count>0));await page.screenshot({path:'/out/operations-real-critical.png',fullPage:true});record('operations-controlled-DB-capacity-corruption-real-dispatcher-durable-critical-survives-unknown');
  await control('OPS_REPAIR_INVARIANT');repaired=true;await sleep(2500);actual=await metric();assert.equal(actual.signals.M2.state,'KNOWN');assert.ok(actual.signals.M2.open.some(e=>e.code==='INVARIANT'));await page.getByText('Có lỗi nghiêm trọng đã biết',{exact:true}).waitFor();record('operations-repaired-authority-ordinary-success-cannot-clear-critical-error');
  await page.route('**/api/v1/admin/operations',route=>route.abort('failed'));await page.getByText('Không có quan sát mới hợp lệ.',{exact:false}).waitFor();await page.getByText('Có lỗi nghiêm trọng đã biết',{exact:true}).waitFor();await page.unroute('**/api/v1/admin/operations');record('operations-source-fetch-loss-keeps-known-critical-no-fake-zero');
  await page.evaluate(()=>globalThis.dispatchEvent(new globalThis.PageTransitionEvent('pagehide',{persisted:true})));assert.equal(await page.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).count(),0);await a.addCookies([{name:'workshop_session',value:'FAKE-LAB-B',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);await page.evaluate(()=>globalThis.dispatchEvent(new globalThis.PageTransitionEvent('pageshow',{persisted:true})));await page.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).waitFor();assert.equal((await metric(b)).actor,'B');record('operations-injected-BFCache-events-clear-private-DOM-reload-current-admin');await page.close();
  // A real actor change during polling must not adopt the other admin silently.
  const switched=await a.newPage();await switched.goto(base+'/operations');await switched.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).waitFor();await a.addCookies([{name:'workshop_session',value:'FAKE-LAB-A',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);await switched.getByText('Cần kiểm tra lại phiên quản trị.',{exact:false}).waitFor();assert.equal(await switched.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).count(),0);record('operations-real-cookie-actor-switch-clears-DOM-before-adopting-metrics');await switched.close();
  const revoked=await a.newPage();await revoked.goto(base+'/operations');await revoked.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).waitFor();let heldResolve;let held=false;const gate=new Promise(resolve=>heldResolve=resolve);let startedResolve;const started=new Promise(resolve=>startedResolve=resolve);
  await revoked.route('**/api/v1/admin/operations',async route=>{if(held)return route.continue();held=true;const r=await route.fetch();const raw=await r.json();startedResolve();await gate;try{await route.fulfill({response:r,json:raw});}catch{/* A timed-out/aborted request is deliberately fenced. */}});
  await started;await control('REVOKE_A');await revoked.getByText('Cần kiểm tra lại phiên quản trị.',{exact:false}).waitFor();assert.equal(await revoked.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).count(),0);heldResolve();await sleep(500);assert.equal(await revoked.getByRole('heading',{name:'Lỗi chưa giải quyết',exact:true}).count(),0);await metric(a,401);record('operations-real-revocation-fences-held-late-response-clears-private-DOM');await control('RESTORE_A');await revoked.close();
  assert.equal(proof.requests.filter(r=>r.method==='POST').length,0);record('operations-dashboard-refresh-and-lifecycle-zero-POST-no-replay-or-clear-API');
 }finally{if(!repaired&&proof.faults.some(f=>f.action==='OPS_FAULT_INVARIANT'))try{await control('OPS_REPAIR_INVARIANT');}catch(error){proof.repairError=error.stack;}writeFileSync('/out/operations-evidence.json',JSON.stringify(proof,null,2));for(const c of contexts)await c.close();}
}
