import https from 'node:https';import http from 'node:http';import {randomBytes,createHash} from 'node:crypto';import assert from 'node:assert/strict';
export const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export async function until(test,label,ms=5000){const start=Date.now();while(Date.now()-start<ms){if(await test())return;await sleep(25);}throw Error('TIMEOUT '+label);}
export class SocketClient {
 constructor(socket,head,{autoAck=true}={}){this.socket=socket;this.messages=[];this.closed=false;this.buffer=Buffer.alloc(0);this.autoAck=autoAck;socket.on('error',e=>{this.error=e.code;});socket.on('close',()=>{this.closed=true;});socket.on('data',data=>this.parse(data));if(head.length)this.parse(head);}
 static open({actor=null,origin='https://workshop.test',path='/api/v1/updates',autoAck=true,component=false}={}){const key=randomBytes(16).toString('base64');return new Promise((resolve,reject)=>{const r=(component?http:https).request({hostname:component?'127.0.0.1':'workshop.test',port:component?8080:443,path,method:'GET',headers:{host:'workshop.test',origin,upgrade:'websocket',connection:'Upgrade','sec-websocket-version':'13','sec-websocket-key':key,...(actor?{cookie:'workshop_session='+actor}:{})}},response=>{response.resume();reject(Error('UPGRADE_HTTP_'+response.statusCode));});r.on('error',reject);r.setTimeout(5000,()=>r.destroy(Error('UPGRADE_TIMEOUT')));r.on('upgrade',(response,socket,head)=>{assert.equal(response.headers['sec-websocket-accept'],createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64'));socket.setTimeout(0);resolve(new SocketClient(socket,head,{autoAck}));});r.end();});}
 parse(data){this.buffer=Buffer.concat([this.buffer,data]);while(this.buffer.length>=2){const opcode=this.buffer[0]&15;assert.equal(this.buffer[1]&128,0,'SERVER_FRAME_MUST_NOT_BE_MASKED');let length=this.buffer[1]&127,offset=2;if(length===126){if(this.buffer.length<4)return;length=this.buffer.readUInt16BE(2);offset=4;}else if(length===127){if(this.buffer.length<10)return;length=Number(this.buffer.readBigUInt64BE(2));offset=10;}assert.ok(length<=1048576,'SERVER_FRAME_OVER_CREDIT_LIMIT');if(this.buffer.length<offset+length)return;const body=this.buffer.subarray(offset,offset+length);this.buffer=this.buffer.subarray(offset+length);if(opcode===8){this.close();return;}assert.equal(opcode,1,'EXPECTED_SERVER_TEXT');const message=JSON.parse(body.toString('utf8'));this.messages.push(message);if(this.autoAck&&message.receipt)this.send({type:'ACK',receipt:message.receipt});}}
 send(value){this.frame(JSON.stringify(value));}
 frame(value,{fin=true,opcode=1}={}){if(this.closed||this.socket.destroyed)return;const body=Buffer.from(value),mask=randomBytes(4),header=Buffer.alloc(body.length<126?6:8);header[0]=(fin?128:0)|opcode;if(body.length<126){header[1]=128|body.length;mask.copy(header,2);}else{assert.ok(body.length<=65535);header[1]=128|126;header.writeUInt16BE(body.length,2);mask.copy(header,4);}const masked=Buffer.alloc(body.length);for(let i=0;i<body.length;i++)masked[i]=body[i]^mask[i%4];this.socket.write(Buffer.concat([header,masked]));}
 subscribe(audience,id,csrf='',epoch='epoch-t02-fixture'){this.send({type:'SUBSCRIBE',audience,epoch,csrf,...(id?{workshopId:id}:{})});}
 snapshots(){return this.messages.filter(v=>v.message.type==='SNAPSHOT').map(v=>v.message.data);}
 close(){this.socket.destroy();}
}
