import fs from 'node:fs';import {readMapSources,traceabilityMap,reverseTrace} from '../../../.agents/skills/kidea/scripts/maps.mjs';
const root='/Users/kendrick/Desktop/kidea-workshop-pilot',dir=process.argv[2];const implementation=JSON.parse(fs.readFileSync(dir+'/web.json'));const docs=JSON.parse(fs.readFileSync(dir+'/documentation.json'));const ref=(path,anchor=null)=>({path,anchor});const test='web/tests/server/public.test.mjs';
const rows=[
 {id:'WEB-INTENT',spec:ref('docs/business/shared/registration.md','retry'),targets:['web/src/lib/state.ts#prepareSend','web/src/lib/Registration.svelte#execute',test],purpose:'Persist identity before POST and reconcile the same request after lost response; explicit action only.',conditions:'Client contract and fake-API Chrome have passed; real HTTPS integration pending. Does not prove backend commit atomicity.',evidence:[ref('web/src/lib/state.ts'),ref('web/src/lib/Registration.svelte'),ref(test)]},
 {id:'WEB-IDENTITY',spec:ref('docs/business/shared/workshop.md','access'),targets:['web/src/lib/server/public.ts#readPublic','web/src/routes/me/+page.server.ts#load','web/src/lib/Registration.svelte',test],purpose:'Keep public SSR anonymous; private history and mutation identity come from the authenticated server session.',conditions:'No client actor/role authority; cookies excluded from public fetch and credentials excluded from SSR payload. Server implementation remains a separate responsibility.',evidence:[ref('web/src/lib/server/public.ts'),ref('web/src/routes/me/+page.server.ts'),ref(test)]},
 {id:'WEB-RESTORE',spec:ref('docs/design/experience.md','error'),targets:['web/src/routes/me/+page.svelte',test],purpose:'Remove private DOM on pagehide and reload against the current server session on persisted pageshow.',conditions:'Explicit PageTransitionEvent handler regression in Chrome, not a claim about every browser BFCache schedule or T05 revocation delivery.',evidence:[ref('web/src/routes/me/+page.svelte'),ref(test)]},
 {id:'WEB-HISTORY',spec:ref('docs/business/features/register-cancel.md','ac'),targets:['web/src/lib/state.ts#ClientState','web/src/lib/reply.ts','web/src/lib/Registration.svelte',test],purpose:'Separate immutable intent result from current versioned registration history; cancellation binds the captured registration ID.',conditions:'Older/conflicting history cannot invent current ACTIVE; event transport and all concurrency schedules remain separate checks.',evidence:[ref('web/src/lib/state.ts'),ref('web/src/lib/reply.ts'),ref(test)]},
 {id:'WEB-SEO',spec:ref('docs/design/experience.md','seo'),targets:['web/src/routes/+page.svelte','web/src/routes/+layout.svelte','web/src/routes/workshops/+page.svelte','web/src/routes/workshops/[id]/+page.svelte',test],purpose:'Readable public HTML, stable lab canonical, noindex and escaped plain content; no private identity in public metadata.',conditions:'Lab policy only, no public indexing or Event markup. Browser tests include JS off, responsive widths and text zoom.',evidence:[ref('web/src/routes/+layout.svelte'),ref(test)]},
 {id:'WEB-EVENT-REMAINING',spec:ref('docs/business/shared/availability.md','reconcile'),targets:[],purpose:'Live public/private event reconciliation and freshness consumers still need T05 wiring.',conditions:'State helper tests alone do not implement or certify live event delivery.',evidence:[ref('web/src/lib/state.ts')]}
];
const all=[...new Set([...implementation.sources,...docs.sources].map(s=>s.path))];const map=traceabilityMap(readMapSources(root,all),implementation,rows,{codeRequired:true});fs.writeFileSync(dir+'/traceability-draft.md','# Responsibility mapping — current Web slice, incomplete\n\nAuthored rows; reverse lookup is derived. Not another task queue or acceptance record. Backend, admin/events/ops and later R09 slices remain to be mapped against actual source.\n\n```json\n'+JSON.stringify(rows,null,2)+'\n```\n',{flag:'wx'});fs.writeFileSync(dir+'/traceability.json',JSON.stringify(map,null,2)+'\n',{flag:'wx'});fs.writeFileSync(dir+'/reverse-registration.json',JSON.stringify(reverseTrace(map,'web/src/lib/Registration.svelte'),null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({rows:rows.length,edges:map.edges.length,diagnostics:map.diagnostics,completeness:map.completeness}));
