import {spawn} from 'node:child_process';import {readFileSync,writeFileSync,createWriteStream} from 'node:fs';import assert from 'node:assert/strict';
const processes=[];let stopping=false;
function start(args,name,env=process.env){const p=spawn(args[0],args.slice(1),{env,cwd:name==='web'?'/web':'/src',stdio:['ignore','pipe','pipe']});p.stdout.pipe(createWriteStream('/out/'+name+'.stdout'));p.stderr.pipe(createWriteStream('/out/'+name+'.stderr'));const done=new Promise(resolve=>p.on('close',(code,signal)=>{writeFileSync('/out/'+name+'.process.json',JSON.stringify({code,signal}));resolve({code,signal});}));p.on('error',()=>{process.exitCode=1;stop();});processes.push({p,done});return {p,done};}
function stop(){if(stopping)return;stopping=true;for(const {p}of processes)if(p.exitCode===null&&p.signalCode===null)p.kill('SIGTERM');}
process.on('SIGTERM',stop);process.on('SIGINT',stop);
const seed=JSON.parse(readFileSync('/src/tests/t02/seed.json'));for(let i=0;i<16;i++){const actor='SOCK-'+i;seed.sessions.push({token:'FAKE-LAB-'+actor,csrf:'FAKE-CSRF-'+actor,actor,participant:true,admin:false,expires:4102444800});}for(const s of seed.sessions)s.expires=Math.floor(Date.now()/1000)+1800;writeFileSync('/out/seed.json',JSON.stringify(seed));
try{
 const init=start(['/backend','--initialize','/out/workshop.sqlite','/src/backend/schema/001.sql','/out/seed.json'],'init');assert.equal((await init.done).code,0);
 const backend=start(['/backend','--serve-component-fixture','/out/workshop.sqlite'],'backend');
 let ready=false;for(let i=0;i<100;i++){try{ready=(await fetch('http://127.0.0.1:8080/api/v1/workshops')).ok;}catch{/* Bounded startup. */}if(ready)break;await new Promise(r=>setTimeout(r,50));}assert.ok(ready);
 const post=async body=>{const r=await fetch('http://127.0.0.1:8080/api/v1/admin/intents',{method:'POST',headers:{cookie:'workshop_session=FAKE-LAB-A','x-csrf-token':'FAKE-CSRF-A',origin:'https://workshop.test','content-type':'application/json'},body:JSON.stringify({epoch:seed.epoch,...body})});assert.equal(r.status,200);return r.json();};
 const created=await post({intentId:'fixture-create',action:'CREATE',fields:{title:'Workshop lập trình thử nghiệm',description:'Dữ liệu giả để kiểm đăng ký, riêng tư và phục hồi ý định.',capacity:1,schedule:{start:'2026-10-01T09:00:00+07:00',end:'2026-10-01T10:00:00+07:00'}}});assert.equal(created.code,'CREATED');const opened=await post({intentId:'fixture-open',action:'STATE',workshopId:created.workshopId,targetState:'OPEN'});assert.equal(opened.code,'UPDATED');writeFileSync('/fixtures/workshop.json',JSON.stringify({id:created.workshopId,title:'Workshop lập trình thử nghiệm'}));
 const web=start(['node','/web/build/index.js'],'web',{...process.env,HOST:'0.0.0.0',PORT:'4173',ORIGIN:'https://workshop.test',WORKSHOP_BACKEND:'http://127.0.0.1:8080',BODY_SIZE_LIMIT:'131072',SHUTDOWN_TIMEOUT:'30'});
 ready=false;for(let i=0;i<100;i++){try{ready=(await fetch('http://127.0.0.1:4173/workshops')).ok;}catch{/* Bounded startup. */}if(ready)break;await new Promise(r=>setTimeout(r,50));}assert.ok(ready);writeFileSync('/fixtures/app-ready.json',JSON.stringify({state:'READY',at:new Date().toISOString()}));
 await Promise.race([backend.done,web.done]);stop();await Promise.all(processes.map(p=>p.done));
}catch(e){writeFileSync('/out/app-error.txt',e.stack);process.exitCode=1;stop();await Promise.all(processes.map(p=>p.done));}
