// Additional endpoint regression against the built C++ server, every preset.
import {spawn} from 'node:child_process';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import assert from 'node:assert/strict';
const [binary,out]=process.argv.slice(2);mkdirSync(out);const db=out+'/session.sqlite';const seed=JSON.parse(readFileSync('/src/tests/t02/seed.json'));for(const s of seed.sessions)s.expires=Math.floor(Date.now()/1000)+300;seed.sessions.push({token:'FAKE-LAB-EXPIRED',csrf:'FAKE-CSRF-EXPIRED',actor:'EXPIRED',participant:true,admin:false,expires:1});writeFileSync(out+'/seed.json',JSON.stringify(seed));
function start(args,label){const p=spawn(binary,args,{stdio:['ignore','pipe','pipe']});let stdout='',stderr='',error=null;p.stdout.on('data',b=>stdout+=b);p.stderr.on('data',b=>stderr+=b);p.on('error',e=>error=e.message);const done=new Promise(resolve=>p.on('close',(code,signal)=>{const r={code,signal,error};writeFileSync(out+'/'+label+'.stdout.txt',stdout);writeFileSync(out+'/'+label+'.stderr.txt',stderr);writeFileSync(out+'/'+label+'.process.json',JSON.stringify(r));resolve({...r,stderr});}));return {p,done};}
const init=start(['--initialize',db,'/src/backend/schema/001.sql',out+'/seed.json'],'init');let timer=setTimeout(()=>init.p.kill('SIGKILL'),10000);const ir=await init.done;clearTimeout(timer);assert.equal(ir.code,0);assert.equal(ir.stderr,'');
const server=start(['--serve-component-fixture',db],'server');timer=setTimeout(()=>server.p.kill('SIGKILL'),20000);const results=[];
const request=async(token,extra={})=>{const r=await fetch('http://127.0.0.1:8080/api/v1/session',{headers:{cookie:token?'workshop_session='+token:'',...extra},signal:AbortSignal.timeout(3000)});return {status:r.status,cache:r.headers.get('cache-control'),body:await r.json()};};
try{
 let ready=false;for(let i=0;i<100;i++){try{ready=(await request('')).status===401;}catch{/* Startup bounded below. */}if(ready)break;await new Promise(r=>setTimeout(r,50));}assert.ok(ready);
 for(const actor of ['U','V','A']){const r=await request('FAKE-LAB-'+actor);assert.equal(r.status,200);assert.equal(r.cache,'no-store');assert.deepEqual(r.body,{actor,epoch:seed.epoch,csrf:'FAKE-CSRF-'+actor,participant:actor!=='A',admin:actor==='A'});assert.ok(!JSON.stringify(r.body).includes('FAKE-LAB-'));results.push({case:'session-'+actor,status:'PASS'});}
 for(const token of ['','UNKNOWN','FAKE-LAB-EXPIRED']){const r=await request(token);assert.equal(r.status,401);assert.equal(r.body.actor,undefined);assert.equal(r.body.csrf,undefined);results.push({case:'denied-'+(token||'missing'),status:'PASS'});}
 const forged=await request('FAKE-LAB-U',{'x-actor':'A','x-role':'admin'});assert.equal(forged.body.actor,'U');assert.equal(forged.body.admin,false);results.push({case:'forged-role-ignored',status:'PASS'});
 const pair=await Promise.all(['U','V'].map(a=>request('FAKE-LAB-'+a)));assert.equal(pair[0].body.actor,'U');assert.equal(pair[1].body.actor,'V');results.push({case:'parallel-session-isolation',status:'PASS'});
}finally{server.p.kill('SIGTERM');const sr=await server.done;clearTimeout(timer);writeFileSync(out+'/results.json',JSON.stringify({results,server:sr},null,2));assert.equal(sr.code,0);assert.equal(sr.signal,null);assert.equal(sr.error,null);assert.equal(sr.stderr,'');}
