import {test} from 'node:test';import assert from 'node:assert/strict';
import {decodeOperations,OperationsCritical} from '../../src/lib/operations.ts';
const now=1800000000000,owner={actor:'A',epoch:'E'};
const sample=()=>({schema:1,profile:'outbox-telemetry-r1',sampledAtMs:now,...owner,writeReady:false,unknown:['M3','M5','M6','M7','M8','M9','BACKEND_ADMISSION_NOT_WIRED'],signals:{M1:{state:'KNOWN',countState:'KNOWN',pending:0,oldestAgeUpperMs:null,oldestAgeLowerMs:null,ageBasis:'EMPTY_NA'},M2:{state:'KNOWN',catalogState:'KNOWN',open:[]},M4:{state:'KNOWN',timeBasis:'PROCESSING_TRANSACTION_TIME',lastSuccess:null}}});
test('confirmed empty means N/A while remaining metrics stay unknown',()=>{assert.ok(decodeOperations(sample(),owner,now));assert.equal(new OperationsCritical().conclusion(sample()),'UNKNOWN');});
test('total pending exceeds batch and conservative age interval is accepted',()=>{const s=sample();s.signals.M1={state:'BOUNDED',countState:'KNOWN',pending:130,oldestAgeUpperMs:40000,oldestAgeLowerMs:31000,ageBasis:'TRANSACTION_START_UPPER_BOUND'};const decoded=decodeOperations(s,owner,now);assert.ok(decoded);const latch=new OperationsCritical();latch.ingest(decoded);assert.equal(latch.conclusion(decoded),'CRITICAL');latch.unknown();assert.equal(latch.conclusion(decoded),'CRITICAL');});
test('an upper bound alone does not prove critical durable age',()=>{const s=sample();s.signals.M1={state:'BOUNDED',countState:'KNOWN',pending:1,oldestAgeUpperMs:40000,oldestAgeLowerMs:null,ageBasis:'TRANSACTION_START_UPPER_BOUND'};assert.ok(decodeOperations(s,owner,now));const latch=new OperationsCritical();latch.ingest(s);assert.equal(latch.conclusion(s),'UNKNOWN');});
test('known invariant persists alongside missing processing observation',()=>{const s=sample();s.signals.M2={state:'UNKNOWN',catalogState:'KNOWN',open:[{code:'INVARIANT',count:1,firstSeenMs:now-10}]};assert.ok(decodeOperations(s,owner,now));assert.equal(new OperationsCritical().conclusion(s),'CRITICAL');});
test('reject cross-identity, stale/future clock, malformed, unsafe numbers and fake health',()=>{const variants=[s=>s.actor='B',s=>s.epoch='OLD',s=>s.sampledAtMs=now-5001,s=>s.sampledAtMs=now+1,s=>s.writeReady=true,s=>s.signals.M1.pending=-1,s=>s.signals.M1.pending=9007199254740992,s=>s.signals.M2.open=[{code:'RAW_SECRET',count:1,firstSeenMs:now}],s=>s.unknown=[],s=>s.extra='payload',s=>s.signals.M4.lastSuccess={atMs:now+1,epoch:'E',workshop:'W',version:'2'},s=>s.signals.M4.lastSuccess={atMs:now,epoch:'E',workshop:'W',version:'18446744073709551616'}];for(const mutate of variants){const s=sample();mutate(s);assert.equal(decodeOperations(s,owner,now),null);}});
test('legacy signals remain explicitly unknown with a known aggregate count',()=>{const s=sample();s.signals={M1:{state:'UNKNOWN',countState:'KNOWN',pending:130,oldestAgeUpperMs:null,oldestAgeLowerMs:null},M2:{state:'UNKNOWN',open:[]},M4:{state:'UNKNOWN'}};assert.ok(decodeOperations(s,owner,now));});
test('critical pending recovery needs three separate source cadences; unknown resets progress',()=>{const latch=new OperationsCritical(),s=sample();s.signals.M1={state:'BOUNDED',countState:'KNOWN',pending:1,oldestAgeLowerMs:30000,oldestAgeUpperMs:31000,ageBasis:'TRANSACTION_START_UPPER_BOUND'};latch.ingest(s);for(const t of [now+1,now+2,now+3]){const ok=sample();ok.sampledAtMs=t;latch.ingest(ok);}assert.equal(latch.conclusion(sample()),'CRITICAL');latch.unknown();for(const t of [now+2000,now+4000]){const ok=sample();ok.sampledAtMs=t;latch.ingest(ok);}assert.equal(latch.conclusion(sample()),'CRITICAL');const ok=sample();ok.sampledAtMs=now+6000;latch.ingest(ok);assert.equal(latch.conclusion(ok),'UNKNOWN');});

test('critical invariant cannot disappear when another valid sample loses the error catalog',()=>{const latch=new OperationsCritical(),bad=sample();bad.signals.M2.open=[{code:'INVARIANT',count:1,firstSeenMs:now-10}];latch.ingest(bad);const lost=sample();lost.sampledAtMs+=2000;lost.signals.M2={state:'UNKNOWN',open:[]};assert.ok(decodeOperations(lost,owner,now+2000));latch.ingest(lost);assert.equal(latch.conclusion(lost),'CRITICAL');});

test('processing success must match current epoch and canonical uint64 identity',()=>{const s=sample();s.signals.M4.lastSuccess={atMs:now,epoch:'E',workshop:'W',version:'18446744073709551615'};assert.ok(decodeOperations(s,owner,now));for(const [epoch,version]of [['OLD','1'],['E','18446744073709551616'],['E','0001'],['E','0'],['E','9'.repeat(100)]]){s.signals.M4.lastSuccess={atMs:now,epoch,workshop:'W',version};assert.equal(decodeOperations(s,owner,now),null);}});
