import test from 'node:test';import assert from 'node:assert/strict';
import {ClientState,decodeHistory,decodeSnapshot,decodeIntent,prepareSend,freshness,version} from '../../src/lib/state.ts';
const h=(extra={})=>({actor:'U',epoch:'E',workshopId:'W',workshopVersion:'1',registrations:[{id:'A',state:'ACTIVE'}],...extra});
const snap=()=>({id:'W',epoch:'E',version:'1',state:'OPEN',title:'Workshop',description:'Nội dung',capacity:1,active:0,remaining:1,observedAt:1,schedule:{start:'2026-10-01T09:00:00+07:00',end:'2026-10-01T10:00:00+07:00'}});
test('decode public snapshot strips optional private additions',()=>{const v=decodeSnapshot({...snap(),actor:'secret',optional:true});assert.deepEqual(v,snap());});
for(const [name,value]of Object.entries({draft:{state:'DRAFT'},overflow:{version:'18446744073709551616'},numeric:{version:1},mixed:{remaining:0},capacity:{capacity:0},schedule:{schedule:{start:'bad',end:'bad'}}}))test('reject snapshot '+name,()=>assert.equal(decodeSnapshot({...snap(),...value}),null));
test('uint64 exact ordering beyond JS integer',()=>{assert.ok(version('18446744073709551615'));const s=new ClientState('U','E');s.merge(h({workshopVersion:'9007199254740992'}),s.context);assert.equal(s.merge(h({workshopVersion:'9007199254740993'}),s.context),'UPDATED');assert.equal(s.merge(h({workshopVersion:'9007199254740992'}),s.context),'IGNORED');});
test('cancel rebook cannot be revived by old response',()=>{const s=new ClientState('U','E');s.merge(h({workshopVersion:'3',registrations:[{id:'A',state:'CANCELLED'},{id:'B',state:'ACTIVE'}]}),s.context);s.merge(h(),s.context);assert.equal(s.history.get('W').registrations[0].state,'CANCELLED');});
test('missing collection group does not erase known history',()=>{const s=new ClientState('U','E');s.merge(h(),s.context);s.collection([],s.context);assert.equal(s.history.size,1);});
test('workshop versions independent',()=>{const s=new ClientState('U','E');s.merge(h({workshopVersion:'99'}),s.context);assert.equal(s.merge(h({workshopId:'W2'}),s.context),'UPDATED');});
test('same version conflicting content remains unknown on repeated original',()=>{const s=new ClientState('U','E');s.merge(h(),s.context);assert.equal(s.merge(h({registrations:[]}),s.context),'UNKNOWN');assert.equal(s.merge(h(),s.context),'UNKNOWN');assert.equal(s.merge(h({workshopVersion:'2'}),s.context),'UPDATED');assert.equal(s.uncertain.size,0);});
for(const mode of ['actor','epoch','login','unmount'])test('late response discarded after '+mode,()=>{const s=new ClientState('U','E');const old={...s.context};s.merge(h(),old);if(mode==='unmount')s.unmount();else s.reset(mode==='actor'?'V':'U',mode==='epoch'?'E2':'E');assert.equal(s.merge(h({workshopVersion:'99'}),old),'IGNORED');if(mode!=='unmount')assert.equal(s.history.size,0);});
for(const registrations of [[{id:'A',state:'ACTIVE'},{id:'A',state:'CANCELLED'}],[{id:'A',state:'ACTIVE'},{id:'B',state:'ACTIVE'}],[{id:'A',state:'BAD'}]])test('reject invalid history '+JSON.stringify(registrations),()=>assert.equal(decodeHistory(h({registrations})),null));
const intent=()=>({actor:'U',epoch:'E',requestId:'X',workshopId:'W',registrationId:null,sent:false,state:'UNKNOWN'});
test('sent persisted before POST; reload can only GET',()=>{const i=intent();let saved;assert.equal(prepareSend(i,v=>saved=v),'POST');const restored=decodeIntent(saved,'U','E');assert.equal(prepareSend(restored,()=>assert.fail()),'GET');assert.equal(restored.requestId,'X');});
test('storage failure blocks mutation',()=>{const i=intent();assert.throws(()=>prepareSend(i,()=>{throw Error('quota');}));assert.equal(i.sent,false);});
test('intent cannot cross actor or restored epoch',()=>{const raw=JSON.stringify(intent());assert.equal(decodeIntent(raw,'V','E'),null);assert.equal(decodeIntent(raw,'U','E2'),null);assert.equal(decodeIntent('{','U','E'),null);});
test('silent and known disconnect never claim fresh',()=>{assert.equal(freshness(null,0,false),'UNKNOWN');assert.equal(freshness(0,5001,false),'UNKNOWN');assert.equal(freshness(0,100,true),'UNKNOWN');assert.equal(freshness(100,0,false),'UNKNOWN');assert.equal(freshness(0,5000,false),'OBSERVED');});

const {scheduleLabel,observationLabel}=await import('../../src/lib/display.ts');
test('schedule preserves both dates and explicit offset',()=>{assert.equal(scheduleLabel('2026-10-01T23:30:00+07:00'),'01/10/2026 23:30 UTC+07:00');assert.equal(scheduleLabel('2026-10-02T01:00:00+08:00'),'02/10/2026 01:00 UTC+08:00');});
test('observation time uses declared UTC and invalid stays unknown',()=>{assert.match(observationLabel(1),/1970-01-01 00:00:01 UTC/);assert.equal(observationLabel(NaN),'Chưa xác nhận thời điểm');});

const {decodeReply}=await import('../../src/lib/reply.ts');
const result=()=>({state:'FINAL',code:'REGISTERED',effect:'APPLIED',workshopId:'W',registrationId:'A'});
test('historical registration result decodes but does not change current history',()=>{const s=new ClientState('U','E');s.merge(h({workshopVersion:'3',registrations:[{id:'A',state:'CANCELLED'}]}),s.context);assert.equal(decodeReply(result(),intent()).code,'REGISTERED');assert.equal(s.history.get('W').registrations[0].state,'CANCELLED');});
for(const extra of [{state:'UNKNOWN'},{effect:'REJECTED'},{workshopId:'other'},{registrationId:''},{code:'CREATED'},{code:'NEW_UNKNOWN_CODE'}])test('uncertain or mismatched reply '+JSON.stringify(extra),()=>assert.equal(decodeReply({...result(),...extra},intent()),null));
test('cancellation reply must match exact registration',()=>{const cancel={...intent(),registrationId:'A'};assert.equal(decodeReply({...result(),code:'CANCELLED'},cancel).registrationId,'A');assert.equal(decodeReply({...result(),code:'CANCELLED',registrationId:'B'},cancel),null);assert.equal(decodeReply(result(),cancel),null);});
