# T05 updates — contract triển khai r1

Phạm vi kỹ thuật theo AR-r2, không thay nghiệp vụ: GET/mutation HTTP vẫn authoritative, WSS `/api/v1/updates` chỉ snapshot/heartbeat. Không mutation hoặc credential trong URL. HTTPS/cookie/Origin qua cổng local đã xác minh; không trust thay đổi trên Mac.

Sau upgrade, client gửi một TEXT frame SUBSCRIBE gồm `type`, `audience` public/admin/private, `epoch`, `csrf`, và `workshopId` cho public/admin. `*` chọn collection đã được quyền HTTP tương ứng; private không nhận workshopId và chỉ trả lịch sử actor của phiên. Origin bắt buộc đúng metadata server. Phiên có cookie phải hợp lệ và CSRF khớp kể cả audience public; cookie sai không tự hạ xuống khách. Khách không có cookie chỉ public, csrf rỗng. Không phát dữ liệu trước SUBSCRIBE hợp lệ.

Server trả envelope `{"message":{...},"receipt":"..."}`; message là SUBSCRIBED, SNAPSHOT hoặc HEARTBEAT, có epoch/audience. SNAPSHOT data cùng schema authoritative HTTP. SUBSCRIBED được phát sau khi subscription tồn tại và trước snapshot/GET đối chiếu. Client subscribe trước rồi GET để khép khe live; HTTP/SSR seed khi kênh chưa sẵn sàng chỉ là quan sát UNKNOWN về cập nhật trực tiếp, SUBSCRIBED vẫn bắt buộc đọc lại. hợp nhất từng workshop/audience/actor/epoch bằng uint64 chuỗi, không thay authority bằng cộng/trừ. Cùng version khác nội dung unknown và GET đối chiếu; response thế hệ cũ không áp vào phiên mới. ACK `{"type":"ACK","receipt":"..."}` chỉ giải phóng frame credit, không chứng minh mutation hoặc browser đã hiển thị.

Receipt ngẫu nhiên an toàn, riêng từng message và được đặt sau toàn payload; chỉ ACK oldest outstanding receipt. Nhờ vậy một peer đọc chậm không dùng cursor đoán được để giải phóng credit cho byte chưa đọc. Tối đa 8 frame chưa ACK và 1MiB gồm envelope/header bảo thủ; quá một trần thì force-close. Heartbeat 2s cũng qua quyền/credit. Không ACK/slow reader không chặn writer. Không thể dùng API public Drogon để đo queue TCP trực tiếp; receipt credit là giới hạn application bao phủ frame đã chuyển sang send. Kernel/Caddy buffers vẫn có giới hạn riêng, không nhận đây là đo RSS toàn hệ thống.

Global pending/active socket tối đa128; trước xác thực16/peer TCP, sau xác thực8/actor; khách16/peer. Frame8KiB,5/s burst10. Với cổng hiện tại, peer TCP là cổng proxy; không tin X-Forwarded-For do client tự khai, nên giới hạn khách có thể chặt hơn theo mạng thực. Chưa nhận profile tải toàn ứng dụng đạt từ contract này. HTTP/subscription dùng Admission đã xác thực, không thêm dashboard/counters nghiệp vụ.

Một worker sở hữu Store, UpdateJournal và socket state. Journal dùng schema1 đã có, không tự migration. Quét tối đa64 outbox row/lượt, coalesce bằng snapshot mới nhất; chưa xử lý còn durable qua restart. No-op/rejected HTTP không tạo event giả. Trước mỗi emit, revalidate token/role/actor/CSRF/epoch; thiếu quyền đóng socket. Đánh dấu completed chỉ nói dispatcher đã xử lý nghĩa vụ cho snapshot hiện tại; không nói mọi browser đã nhận. Crash giữa send và mark có thể gửi lại snapshot; client bỏ cũ/lặp. Không xóa row/result/audit. Lỗi storage/exception khi phát để pending và đóng kênh; quá credit hoặc mất quyền đóng client, nghĩa vụ dispatcher có thể đã xử lý nhưng client vẫn cần GET đối chiếu, client chuyển unknown/GET đối chiếu. Restore đổi epoch cần thủ tục reconciliation outbox được kiểm ở T08, không ngầm miễn readiness.

Kiểm r1 dự kiến: đủ 50 CTest/856 assertion T04 và toàn HTTP/session/shutdown cũ, thêm unit quyền/epoch/credit/quota/rate/journal; dev/tidy, ASan/UBSan/TSan/release. New code không được mở rộng EX r2. Thêm HTTPS browser/socket tests trên artifact cuối; tài liệu này không PASS thay runtime. T05 tổng thể còn monitoring/backup/readiness/restore và ma trận còn thiếu.
