from pathlib import Path
import json,re,hashlib,subprocess,time,os
repo=Path('/Users/kendrick/Desktop/kidea');selected='/Users/kendrick/Desktop/kidea-workshop-pilot';node='/Users/kendrick/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node';helper=repo/'.agents/skills/kidea/scripts/kidea.mjs'
p=Path(subprocess.check_output([node,'-e','process.stdout.write(require("node:fs").realpathSync(process.argv[1]))',selected],text=True));out=repo/'tests/evidence/r09/t05-real-telemetry-r1/finalization-r2';out.mkdir();timings=[]
sha=lambda data:hashlib.sha256(data).hexdigest()
def data(path):return json.loads(re.search(r'```json\n([\s\S]*?)\n```',path.read_text())[1])
def history_hash(v):
 loc=v['location'];body=subprocess.check_output(['git','-C',str(p),'show',loc['commit']+':'+loc['path']])if loc['kind']=='GIT'else(p/loc['ref']['path']).read_bytes();assert sha(body)==v['integrity']['value'];return {'location':loc,'sha256':sha(body),'bytes':len(body)}
def budget():
 a=json.loads((repo/'tests/evidence/r09/full-scope/authorization.json').read_text());sizes={k:int(subprocess.check_output(['du','-sk',k],text=True).split()[0])*1024 for k in a['baselineAllocatedBytes']};used=sum(max(0,v-a['baselineAllocatedBytes'][k])for k,v in sizes.items());s=os.statvfs(repo);free=s.f_bavail*s.f_frsize;assert used+128*1024**2<a['cumulativeNewDiskLimitBytes']and free>=a['minimumFreeBytes'];return{'newBytes':used,'freeBytes':free,'baselineUnchanged':True,'gitReserveBytes':128*1024**2}
def call(action,name,request):
 budget();(out/(name+'-request.json')).write_text(json.dumps(request,indent=2)+'\n');print('public',name,'start',flush=True);started=time.monotonic()
 r=subprocess.run([node,str(helper),action],cwd=p,input=json.dumps(request),text=True,capture_output=True,timeout=14400)
 timing={'name':name,'seconds':time.monotonic()-started,'exit':r.returncode};timings.append(timing);(out/'public-helper-timing.json').write_text(json.dumps({'scope':'Actual bounded public workflow timing; not WQ or performance PASS','timings':timings},indent=2)+'\n')
 (out/(name+'-result.json')).write_text(json.dumps({'exit':r.returncode,'stdout':r.stdout,'stderr':r.stderr},indent=2)+'\n');assert r.returncode==0,(name,r.stderr);v=json.loads(r.stdout);print('public',name,v['state'],timing['seconds'],flush=True);return v
folder='tests/t05/real-telemetry-evidence-r1/'
report={'path':'tests/t05/real-telemetry-checkpoint-r1.md','anchor':None}
evidence=[{'path':folder+n,'anchor':None}for n in ['source.json','checks.json','integration.json','backend-results.json','backend-manifest.json','coverage-preservation.json','facets.md']]
proof=json.loads((p/folder/'checks.json').read_text());assert proof['status']=='PASS';assert proof['backendPresets']==4 and proof['telemetryChecksPerPreset']==167 and proof['nativeFinalTests']==40
source=[{'path':n,'anchor':None}for n in subprocess.check_output(['git','diff','--name-only','aba73cf246f2ccfd8a30d0322048dc0a5934bebb','--','backend','contracts','scripts/t05','docs/t05','web/src','web/tests/unit/operations.test.mjs'],cwd=p,text=True).splitlines()]
refs=[report]+evidence+source
for ref in refs:assert(p/ref['path']).is_file()
review_path=p/'.kidea/reviews/R09-T04-OUTPUT-r1.md';old=data(review_path);assert old['revision']==9 and old['status']=='DRAFT';prepared=json.loads((repo/'tests/evidence/r09/t05-real-telemetry-r1/review-preparation.json').read_text());assert sha(review_path.read_bytes())==prepared['digestAtRead'];work_before=data(p/'.kidea/work.md')
reviews_before={str(f.relative_to(p)):sha(f.read_bytes())for f in(p/'.kidea/reviews').rglob('*.md')};history_before=[history_hash(v)for v in old['historyRefs']];current=[];changed=[]
for v in old['subjectVersions']+old['inputVersions']:
 loc=v['location'];before=subprocess.check_output(['git','-C',str(p),'show',loc['commit']+':'+loc['path']])if loc['kind']=='GIT'else(p/loc['ref']['path']).read_bytes();assert sha(before)==v['integrity']['value'];now=(p/v['source']['path']).read_bytes();current.append({'ref':v['source'],'integrity':{'method':'SHA256','value':sha(now),'byteLength':len(now)}})
 if before!=now:changed.append(v['source']['path'])
assert changed==[v['path']for v in prepared['changedSources']]
def unique(refs):
 seen=set();result=[]
 for ref in refs:
  key=(ref['path'],ref['anchor'])
  if key not in seen:seen.add(key);result.append(ref)
 return result
permission={'root':str(p),'reviewPath':str(review_path.relative_to(p)),'ownerIds':old['ownerIds'],'allowReviewMetadata':True,'allowCreateEvidence':True,'createDirectories':[],'allowReadLocalGit':True,'assumptions':{'localFilesystem':True,'noActiveSync':True,'singleKideaRun':True},'statement':'Human full R09 execution grant and current Lam tiep di authorize additive real C++ telemetry/primary Web implementation, tests, bounded public review/continuation metadata, local pilot commit and Kidea commit/push. REVISE only to revision10 DRAFT; preserve accepted T04 history, owners, gates, blockers and resource baseline. No Human acceptance/COMPLETE/PROD/oncall, install, cloud or deployment.'}
package={'subjectRefs':unique(old['subjectRefs']+[report]+evidence[:5]+source),'inputRefs':unique([v['source']for v in old['inputVersions']]+evidence[5:]),'purpose':old['purpose'],'waiverReason':None}
comparison='Read every fixed old/current source in order including duplicates. Store writer adds transactionally durable telemetry, exact schema hash changes only for new CREATE-only profile; existing schema1 remains business-compatible with unknown unavailable signals, no migration/reset. Dispatcher adds durable real event-identity PROCESSING/INVARIANT/RECONCILE catalog and capacity-authority validation; ordinary success resolves only exact PROCESSING errors and cannot clear critical incidents. Exact pending total replaces batch64 as metric; age is a conservative transaction/first-observation interval, never claimed exact commit age. M4 is processing identity/time, never browser receipt. OpenAPI adds admin-only GET operations; primary Svelte W5 adds actor/epoch-bound no-store SSR/read-only polling, strict stale/clock/identity guards, private DOM clearing/fences and retained known critical detail. New source/tests/build retain all old cases/EXr2; fresh four backend presets and real TLS integration pass, 102 units and40native fake-API tests pass; every FAIL retained. Sourceprofile and exact schema/config changed semantically, so reopen DRAFT and preserve original acceptance/history. M2 producers partial; M3/M5/M6/M7/M8/M9/admission remain UNKNOWN, fallback observer unchanged/not bridged, writeReady false. Original137coverage not promoted; backup/admission/WQ/E1/independent host/Human oncall/PROD/G2/T08/final acceptance remain missing. No business rule, permission, safety exception or budget change.'
r=call('approve','review-revise-r10',{'operation':'REVISE','id':old['id'],'revision':old['revision'],'expectedDigest':prepared['digestAtRead'],'ownerIds':old['ownerIds'],'package':package,'comparison':{'reason':comparison,'affectedIds':old['ownerIds']+['W-009','W-009-MAX2','W-009-ADMIN-OPS','W-009-G2'],'currentSources':current},'permission':permission})
assert r['state']=='REVIEW_RECORDED';new=data(review_path);assert new['revision']==10 and new['status']=='DRAFT'and new['ownerIds']==old['ownerIds'];assert data(p/'.kidea/work.md')==work_before;assert new['historyRefs'][:len(old['historyRefs'])]==old['historyRefs'];assert [history_hash(v)for v in new['historyRefs'][:len(old['historyRefs'])]]==history_before
for path,h in reviews_before.items():
 if path!=str(review_path.relative_to(p)):assert sha((p/path).read_bytes())==h,path
read={'operation':'READ','permission':{'root':str(p),'readProject':True,'allowReadLocalGit':True},'requiredFiles':refs};r=call('resume','resume-read-final',read);assert r['state']=='WAITING';c=r['context'];assert c['currentItem']['id']=='W-009-ADMIN-OPS';reviews_presave={str(f.relative_to(p)):sha(f.read_bytes())for f in(p/'.kidea/reviews').rglob('*.md')}
request={**read,'operation':'SAVE','expectedBasis':r['basis'],'expectedProjectId':c['projectId'],'expectedGit':c['checkout'],'permission':{**read['permission'],'allowSaveContinuation':True,'assumptions':{'localFilesystem':True,'noActiveSync':True,'singleKideaRun':True},'statement':'Human full R09 execution plus current continue authorize saving the verified partial real telemetry/primary W5 milestone. Change only current work nextAction/checkpointRef and generated bounded checkpoint evidence; preserve all owners/statuses/gates/blockers/return stack/review/history. No Human acceptance, task completion, oncall, PROD or deployment.'},'checkpoint':{'itemId':'W-009-ADMIN-OPS','completed':proof['completed'],'remaining':proof['remaining'],'nextAction':proof['nextAction'],'sourceRefs':refs}}
r=call('resume','resume-save-final',request);assert r['state']=='CONTINUATION_SAVED';after=data(p/'.kidea/work.md');assert set(after)==set(work_before);fields=[k for k in work_before if after[k]!=work_before[k]];assert set(fields)=={'nextAction','checkpointRef'};assert {str(f.relative_to(p)):sha(f.read_bytes())for f in(p/'.kidea/reviews').rglob('*.md')}==reviews_presave
(out/'preservation.json').write_text(json.dumps({'status':'PASS','oldFixedVersionsRead':len(current),'semanticSourceChanges':changed,'reviewRevision':10,'reviewStatus':'DRAFT','allOtherReviewsAndHistoryUnchanged':True,'selectedPriorHistoryRefsPreserved':True,'oldHistoryFileHashes':history_before,'changedWorkFields':fields,'allOtherWorkDataUnchanged':True,'currentOwner':'W-009-ADMIN-OPS','executionStatus':'IN_PROGRESS','notHumanAcceptance':True,'budget':budget()},indent=2)+'\n');print('public finalization PASS',flush=True)
