import {createRequire} from 'node:module';import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire('/web/package.json');const {chromium}=require('playwright');
const fixture=JSON.parse(readFileSync('/fixtures/workshop.json'));const base='https://workshop.test';const checks=[],pageErrors=[],external=[],requests=[];
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
async function context(actor,options={}){const c=await browser.newContext({baseURL:base,...options});c.on('page',p=>{p.on('pageerror',e=>pageErrors.push(e.message));p.on('request',r=>{const url=new URL(r.url());if(url.origin!==base)external.push(r.url());if(url.pathname.startsWith('/api/'))requests.push({initialContextActor:actor,method:r.method(),path:url.pathname,body:r.method()==='POST'?r.postData():null});});});if(actor)await c.addCookies([{name:'workshop_session',value:'FAKE-LAB-'+actor,domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);return c;}
const record=name=>checks.push({name,status:'PASS'});
async function ready(page){await page.goto(base+'/workshops/'+fixture.id);await page.getByRole('link',{name:'Xem đăng ký của tôi'}).waitFor();}
async function api(c,path){const r=await c.request.get(base+'/api/v1'+path);assert.equal(r.status(),200);return r.json();}
try{
 const anonymous=await context(null,{javaScriptEnabled:false});const p=await anonymous.newPage();const response=await p.goto(base+'/workshops/'+fixture.id);assert.equal(response.status(),200);await p.getByRole('heading',{name:fixture.title,exact:true}).waitFor();const html=await p.content();assert.ok(!html.includes('FAKE-CSRF')&&!html.includes('FAKE-LAB'));assert.equal(await p.getByRole('link',{name:'Xem đăng ký của tôi'}).count(),0);record('public-SSR-JS-off-TLS');await anonymous.close();
 const u=await context('U'),v=await context('V');const up=await u.newPage(),vp=await v.newPage();await Promise.all([ready(up),ready(vp)]);assert.equal((await api(u,'/session')).actor,'U');assert.equal((await api(v,'/session')).actor,'V');assert.ok((await u.cookies()).every(c=>c.secure&&c.httpOnly));assert.equal(await up.evaluate(()=>document.cookie),'');record('server-session-cookie-isolation');
 let writes=0,lostId;await up.route('**/api/v1/registrations',async route=>{if(route.request().method()!=='POST')return route.continue();writes++;lostId=route.request().postDataJSON().requestId;const actual=await route.fetch();assert.equal(actual.status(),200);const body=await actual.json();assert.equal(body.code,'REGISTERED');await route.abort('failed');});
 await up.getByRole('button',{name:'Đăng ký',exact:true}).click();await up.getByText('Chưa xác nhận kết quả. Không tự gửi lại thao tác.',{exact:true}).waitFor();assert.equal(writes,1);await up.reload();await up.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();assert.equal(writes,1);await up.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).click();await up.getByRole('button',{name:'Hủy đăng ký',exact:true}).waitFor();assert.equal(writes,1);const first=await api(u,'/requests/'+lostId);assert.equal(first.code,'REGISTERED');record('real-commit-lost-response-reload-GET-only');await up.unroute('**/api/v1/registrations');
 await vp.getByRole('button',{name:'Đăng ký',exact:true}).click();await vp.getByText('Không còn chỗ tại thời điểm xử lý.',{exact:false}).waitFor();record('last-seat-FULL-other-user');
 let cancellations=0;await up.route('**/api/v1/registrations/*/cancel',async route=>{cancellations++;assert.ok(route.request().url().endsWith('/'+first.registrationId+'/cancel'));await route.continue();});await up.getByRole('button',{name:'Hủy đăng ký',exact:true}).click();await up.keyboard.press('Escape');assert.equal(cancellations,0);await up.getByRole('button',{name:'Hủy đăng ký',exact:true}).click();await up.getByRole('button',{name:'Xác nhận hủy',exact:true}).click();await up.getByText('Lần đó hủy đăng ký thành công.',{exact:false}).waitFor();assert.equal(cancellations,1);record('Escape-no-write-exact-id-cancel');
 await up.getByRole('button',{name:'Đăng ký',exact:true}).click();await up.getByText('Lần đó đăng ký thành công.',{exact:false}).waitFor();const history=await api(u,'/me/registrations');writeFileSync('/out/history.json',JSON.stringify(history,null,2));const old=await api(u,'/requests/'+lostId);assert.deepEqual(old,first);assert.ok(Array.isArray(history));const group=history.find(g=>g.workshopId===fixture.id);assert.ok(group);assert.equal(group.actor,'U');assert.equal(group.registrations.length,2);assert.equal(group.registrations.find(r=>r.id===first.registrationId)?.state,'CANCELLED');const active=group.registrations.filter(r=>r.state==='ACTIVE');assert.equal(active.length,1);assert.notEqual(active[0].id,first.registrationId);record('cancel-rebook-old-result-immutable');
 await Promise.all([up.goto(base+'/me'),vp.goto(base+'/me')]);const [uh,vh]=await Promise.all([up.content(),vp.content()]);assert.ok(uh.includes(first.registrationId));assert.ok(!vh.includes(first.registrationId));for(const text of [uh,vh])assert.ok(!text.includes('FAKE-CSRF')&&!text.includes('FAKE-LAB'));record('private-SSR-no-cross-user-data');
 const forged=await u.request.get(base+'/api/v1/session',{headers:{'x-forwarded-host':'evil.test'}});assert.equal(forged.status(),400);const csrf=await u.request.post(base+'/api/v1/registrations',{headers:{origin:base,'x-csrf-token':'wrong'},data:{epoch:'epoch-t02-fixture',requestId:'wrong-csrf',workshopId:fixture.id}});assert.equal(csrf.status(),401);record('proxy-forgery-and-CSRF-denied');
 await up.screenshot({path:'/out/private.png',fullPage:true});
 await up.evaluate(()=>globalThis.dispatchEvent(new globalThis.PageTransitionEvent('pagehide',{persisted:true})));assert.equal(await up.getByText(first.registrationId+' · Đã hủy',{exact:true}).count(),0);
 await u.addCookies([{name:'workshop_session',value:'FAKE-LAB-V',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);await up.evaluate(()=>globalThis.dispatchEvent(new globalThis.PageTransitionEvent('pageshow',{persisted:true})));await up.getByText('Chưa có đăng ký trong phiên hiện tại.',{exact:true}).waitFor();assert.ok(!(await up.content()).includes(first.registrationId));record('restored-page-server-revalidates-new-actor');
 await u.addCookies([{name:'workshop_session',value:'REVOKED-UNKNOWN',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);assert.equal((await up.reload()).status(),401);assert.ok(!(await up.content()).includes(first.registrationId));record('invalid-session-clears-private-page');
 assert.deepEqual(pageErrors,[]);assert.deepEqual(external,[]);record('no-page-error-or-external-request');writeFileSync('/out/result.json',JSON.stringify({status:'PASS',checks,browser:browser.version(),tlsBypass:false},null,2));
}catch(e){writeFileSync('/out/result.json',JSON.stringify({status:'FAIL',checks,error:e.stack},null,2));throw e;}finally{writeFileSync('/out/requests.json',JSON.stringify(requests,null,2));await browser.close();}
