import {encodeReceipt} from './control-receipt.mjs';
import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {createHash,randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
const plan=import.meta.dirname,repo=path.resolve(plan,'../../..'),pilot='/Users/kendrick/Desktop/kidea-workshop-pilot';
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function inventory(root){const result={};function walk(dir){for(const name of fs.readdirSync(dir).sort()){const p=path.join(dir,name),s=fs.lstatSync(p),key=path.relative(root,p);if(s.isSymbolicLink())result[key]={link:fs.readlinkSync(p)};else if(s.isDirectory())walk(p);else if(s.isFile())result[key]={sha256:sha(p),mode:s.mode&511};}}walk(root);return result;}
const [manifestPath,expected]=process.argv.slice(2);assert.equal(sha(manifestPath),expected);const manifest=JSON.parse(fs.readFileSync(manifestPath));assert.notEqual(process.getuid(),0);
const auth=JSON.parse(fs.readFileSync(repo+'/tests/evidence/r09/full-scope/authorization.json'));
const started=Date.now(),id='r09-web-'+randomUUID(),out=repo+'/.test-output/'+id;fs.mkdirSync(out);for(const d of ['logs','app','browser','ca','fixtures']){fs.mkdirSync(out+'/'+d);fs.chmodSync(out+'/'+d,0o777);}
const owned=[],network=id;let controlTimer=null,controlBusy=false,controlId=0;let networkOwned=false,seq=0,error=null;
function budget(){const used=Object.entries(auth.baselineAllocatedBytes).reduce((sum,[p,b])=>sum+Math.max(0,Number(execFileSync('du',['-sk',p],{encoding:'utf8'}).split(/\s/)[0])*1024-b),0),s=fs.statfsSync(repo),free=s.bavail*s.bsize;assert.ok(used<auth.cumulativeNewDiskLimitBytes,'CUMULATIVE_DISK');assert.ok(free>=auth.minimumFreeBytes,'FREE_DISK');assert.ok(Date.now()-started<1800000,'RUN_DEADLINE');return {used,free};}
function verify(){assert.deepEqual(inventory(pilot+'/web/src'),manifest.webSource);for(const [p,h]of Object.entries(manifest.files))assert.equal(sha(p),h,p);assert.deepEqual(inventory(pilot+'/web/build'),manifest.webBuild);assert.deepEqual(inventory(pilot+'/web/node_modules'),manifest.webDependencies);}
async function docker(args,cleanup=false){if(!cleanup)budget();const result=await new Promise(resolve=>{const p=spawn('docker',args,{stdio:['ignore','pipe','pipe']});let stdout='',stderr='',failure=null;const timer=setTimeout(()=>{failure='TIMEOUT';p.kill('SIGKILL');},args[0]==='wait'?180000:60000);for(const [stream,key]of [[p.stdout,'stdout'],[p.stderr,'stderr']])stream.on('data',d=>{if(key==='stdout')stdout+=d;else stderr+=d;if(stdout.length+stderr.length>8*1024**2){failure='LOG_LIMIT';p.kill('SIGKILL');}});p.on('error',e=>failure=e.message);p.on('close',code=>{clearTimeout(timer);resolve({code,stdout,stderr,failure});});});fs.writeFileSync(out+'/logs/'+String(++seq).padStart(3,'0')+'.json',JSON.stringify({args,...result},null,2));assert.ok(result.code===0&&!result.failure,JSON.stringify({args,...result}));return result.stdout.trim();}
async function start(role,image,command,mounts,env=[]){const name=id+'-'+role;const args=['create','--pull=never','--platform=linux/amd64','--log-opt=max-size=8m','--log-opt=max-file=2','--name',name,'--label','kidea.r09.owner='+id,'--network',network,'--network-alias',role==='caddy'?'workshop.test':role,'--cpus',role==='app'?'2':'1','--memory',role==='app'?'4g':'2g','--memory-swap',role==='app'?'4g':'2g','--pids-limit','256','--read-only','--user','1000:1000','--cap-drop','ALL','--security-opt','no-new-privileges','--tmpfs','/tmp:rw,nosuid,size=512m','--shm-size','256m'];for(const [src,dst,writable=false]of mounts)args.push('--mount',`type=bind,src=${src},dst=${dst}${writable?'':',readonly'}`);for(const e of env)args.push('-e',e);args.push('--entrypoint','timeout',image,'--signal=TERM','--kill-after=35','1200',...command);const cid=await docker(args);owned.push({name,cid,role});await docker(['start',cid]);return cid;}
async function awaitFile(p,cid){for(let i=0;i<100;i++){if(fs.existsSync(p))return;const state=JSON.parse(await docker(['inspect',cid,'--format','{{json .State}}']));assert.ok(state.Running,'APP_EXITED '+JSON.stringify(state));await new Promise(r=>setTimeout(r,200));}throw Error('READY_TIMEOUT '+p);}
try{
 verify();assert.ok(budget().used+2*1024**3<auth.cumulativeNewDiskLimitBytes,'RESERVE_2GiB');assert.equal(await docker(['ps','-q']),'','OTHER_ACTIVE_WORKLOAD');for(const image of [manifest.image,manifest.browserImage])assert.equal(await docker(['image','inspect',image,'--format','{{.Id}}']),image);
 await docker(['network','create','--internal','--label','kidea.r09.owner='+id,network]);networkOwned=true;
 const tools=repo+'/.test-output/r08-delivery-inputs-r1';const common=[[plan,'/plan'],[pilot,'/src'],[pilot+'/web','/web']];
 const app=await start('app',manifest.image,['node','/plan/app.mjs'],[...common,[manifest.backend,'/backend'],[out+'/app','/out',true],[out+'/fixtures','/fixtures',true]]);await awaitFile(out+'/fixtures/app-ready.json',app);
 const caddy=await start('caddy',manifest.image,['/caddy','run','--config','/plan/Caddyfile','--adapter','caddyfile'],[[plan,'/plan'],[tools+'/caddy','/caddy'],[out+'/ca','/data',true]],['XDG_DATA_HOME=/data','XDG_CONFIG_HOME=/tmp/config']);await docker(['exec',caddy,'sh','-c','i=0; while [ ! -f /data/caddy/pki/authorities/local/root.crt ]; do i=$((i+1)); [ "$i" -le 100 ] || exit 1; sleep 0.1; done']);await docker(['cp',caddy+':/data/caddy/pki/authorities/local/root.crt',out+'/fixtures/root.crt']);
 controlTimer=setInterval(()=>{if(controlBusy||!fs.existsSync(out+'/browser/control-request.json'))return;controlBusy=true;void(async()=>{try{const request=JSON.parse(fs.readFileSync(out+'/browser/control-request.json'));if(request.id<=controlId)return;assert.equal(request.id,controlId+1);assert.deepEqual(Object.keys(request).sort(),['action','id']);const info=JSON.parse(await docker(['inspect',app],true))[0];assert.equal(info.Config.Labels['kidea.r09.owner'],id);assert.ok(['PAUSE_APP','UNPAUSE_APP','REVOKE_V','REVOKE_A','RESTORE_A'].includes(request.action));const disk=fs.statfsSync(repo);assert.ok(disk.bavail*disk.bsize>=auth.minimumFreeBytes,'CONTROL_FREE_DISK');assert.ok(Date.now()-started<1800000,'CONTROL_DEADLINE');if(request.action==='PAUSE_APP')await docker(['pause',app],true);else if(request.action==='UNPAUSE_APP')await docker(['unpause',app],true);else {const actor=request.action==='REVOKE_V'?'V':'A',revoked=request.action==='RESTORE_A'?0:1;await docker(['exec',app,'python3','-c',"import sqlite3; db=sqlite3.connect('/out/workshop.sqlite',timeout=1); db.execute('UPDATE sessions SET revoked=? WHERE actor=?',("+revoked+",'"+actor+"')); db.commit(); db.close()"],true);}controlId=request.id;const resultFile=out+'/browser/control-result-'+controlId+'.tmp';fs.writeFileSync(resultFile,encodeReceipt({id:controlId,action:request.action,status:'DONE',at:new Date().toISOString()}),{flag:'wx'});fs.renameSync(resultFile,out+'/browser/control-result-'+controlId+'.receipt');}catch(e){fs.writeFileSync(out+'/browser/control-error.txt',e.stack);}finally{controlBusy=false;}})();},100);
 const browser=await start('browser',manifest.browserImage,['sh','/plan/browser-bootstrap.sh'],[[plan,'/plan'],[pilot+'/web','/web'],[tools+'/node','/opt/node/bin/node'],[tools+'/certutil','/usr/local/bin/certutil'],[out+'/fixtures','/fixtures'],[out+'/browser','/out',true]],['PATH=/opt/node/bin:/usr/local/bin:/usr/bin:/bin']);assert.equal(Number(await docker(['wait',browser])),0,'BROWSER_EXIT');assert.equal(JSON.parse(fs.readFileSync(out+'/browser/result.json')).status,'PASS');verify();
}catch(e){error=e.stack;}finally{
 if(controlTimer!==null)clearInterval(controlTimer);while(controlBusy)await new Promise(r=>setTimeout(r,25));
 for(const item of owned.reverse()){try{const info=JSON.parse(await docker(['inspect',item.cid],true))[0];assert.equal(info.Config.Labels['kidea.r09.owner'],id);if(info.State.Paused)await docker(['unpause',item.cid],true);if(info.State.Running)await docker(['stop','--time=35',item.cid],true);fs.writeFileSync(out+'/logs/'+item.role+'.txt',await docker(['logs',item.cid],true));fs.writeFileSync(out+'/logs/'+item.role+'-state.json',await docker(['inspect',item.cid],true));await docker(['rm',item.cid],true);}catch(e){error=(error||'')+'\nCLEANUP '+e.stack;}}
 if(networkOwned)try{await docker(['network','rm',network],true);}catch(e){error=(error||'')+'\nNETWORK '+e.stack;}
 fs.writeFileSync(out+'/result.json',JSON.stringify({id,manifestHash:expected,started:new Date(started).toISOString(),ended:new Date().toISOString(),status:error?'FAIL':'PASS',error},null,2));console.log(out);if(error){console.error(error);process.exitCode=1;}
}
