// Read-only real pilot receipts; no compiler, metadata writer, or executable config.
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';
import {readMapSources,documentationMap} from '../../../.agents/skills/kidea/scripts/maps.mjs';import {webMap} from '../../../.agents/skills/kidea/scripts/maps-web.mjs';
const root='/Users/kendrick/Desktop/kidea-workshop-pilot',out=process.argv[2],require=createRequire(root+'/web/package.json');const ts=require('typescript'),svelte=require('svelte/compiler');
function files(dir){return fs.readdirSync(root+'/'+dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>e.isDirectory()?files(dir+'/'+e.name):[dir+'/'+e.name]);}
const spec=['docs/features.md',...['docs/business','docs/design','docs/engineering'].flatMap(files)].filter(p=>p.endsWith('.md'));const web=[...files('web/src'),'web/tsconfig.json','web/package.json','web/package-lock.json','web/svelte.config.js','web/vite.config.ts'];
const capabilities=['typescript','svelte/compiler'].map(id=>{const p=require.resolve(id),bytes=fs.readFileSync(p);return {id,path:p,sha256:createHash('sha256').update(bytes).digest('hex')};});
const docs= documentationMap(readMapSources(root,spec));const implementation=webMap(readMapSources(root,web),{ts,svelte,tool:{version:'typescript'+ts.version+'/svelte'+svelte.VERSION,components:capabilities},tsconfig:'web/tsconfig.json'});
for(const [name,value]of Object.entries({documentation:docs,web:implementation}))fs.writeFileSync(out+'/'+name+'.json',JSON.stringify(value,null,2)+'\n',{flag:'wx'});
const summary={root,createdAt:new Date().toISOString(),specSources:spec.length,webSources:web.length,documentation:{nodes:docs.nodes.length,edges:docs.edges.length,diagnostics:docs.diagnostics.length,completeness:docs.completeness},web:{nodes:implementation.nodes.length,edges:implementation.edges.length,diagnostics:implementation.diagnostics.length,completeness:implementation.completeness},cpp:'NOT_RUN_REQUIRES_BOUND_CLANG_RECEIPT',traceability:'NOT_AUTHORED',semanticReview:'REQUIRED',notT14Acceptance:true};fs.writeFileSync(out+'/summary.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(summary));
