// Built Web/native Mac Chrome + explicit fake API; not a backend/TLS test.
import test from 'node:test';import assert from 'node:assert/strict';
import {createServer} from 'node:http';import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';import path from 'node:path';
const web=process.env.WORKSHOP_WEB_ROOT;assert.ok(web&&path.isAbsolute(web));
const {chromium}=createRequire(web+'/package.json')('playwright');
const snapshot={id:'W',epoch:'E',version:'1',state:'DRAFT',title:'Initial title',description:'Fake test content',capacity:10,active:0,remaining:10,observedAt:1,schedule:{start:'2026-11-04T09:00:00+07:00',end:'2026-11-04T10:00:00+07:00'}};
let current={...snapshot},receiptUnavailable=false;const remembered=new Map(),requests=[];
const api=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;requests.push({method:req.method,url:req.url});res.setHeader('content-type','application/json');const reply=(status,body)=>{res.statusCode=status;res.end(JSON.stringify(body));};
 if(req.url==='/api/v1/session')return reply(200,{actor:'A',epoch:'E',csrf:'FAKE-CSRF-A',admin:true,participant:false});
 if(req.url==='/api/v1/admin/workshops/W')return reply(200,current);
 if(req.url==='/api/v1/admin/intents'&&req.method==='POST'){const c=JSON.parse(raw);if(c.action==='EDIT'){current={...current,...c.fields,version:String(Number(current.version)+1)};const r={state:'FINAL',code:'UPDATED',effect:'APPLIED',workshopId:'W'};remembered.set(c.intentId,r);return reply(200,r);}return reply(503,{state:'UNKNOWN',code:'UNCONFIRMED'});}
 if(req.url?.startsWith('/api/v1/admin/intents/')){const id=req.url.slice('/api/v1/admin/intents/'.length);if(receiptUnavailable&&remembered.has(id))return reply(503,{state:'UNKNOWN',code:'UNCONFIRMED'});return remembered.has(id)?reply(200,remembered.get(id)):reply(202,{state:'UNKNOWN',code:'UNCONFIRMED'});}
 return reply(404,{state:'ERROR',code:'UNAVAILABLE'});
});await new Promise(r=>api.listen(0,'127.0.0.1',r));
const reserve=createServer();await new Promise(r=>reserve.listen(0,'127.0.0.1',r));const port=reserve.address().port;await new Promise(r=>reserve.close(r));const base='http://127.0.0.1:'+port;
const child=spawn(process.execPath,['build/index.js'],{cwd:web,env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ORIGIN:'https://workshop.test',WORKSHOP_BACKEND:'http://127.0.0.1:'+api.address().port},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);const closed=new Promise(r=>child.on('close',r));let browser;
const marker={actor:'A',epoch:'E',command:{epoch:'E',intentId:'EDIT-KNOWN',action:'EDIT',workshopId:'W',fields:{title:'Saved content'}},sent:true,state:'FINAL'};
async function page(){const c=await browser.newContext();await c.addCookies([{name:'workshop_session',value:'FAKE-LAB-A',url:base,httpOnly:true}]);const p=await c.newPage();await p.route('**/api/v1/**',async route=>{const url=new URL(route.request().url());const actual=await route.fetch({url:'http://127.0.0.1:'+api.address().port+url.pathname});await route.fulfill({response:actual});});return {p,c};}
try{
 let ready=false;for(let n=0;n<100;n++){try{ready=(await fetch(base)).ok;}catch{}if(ready)break;await new Promise(r=>setTimeout(r,50));}assert.ok(ready);browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 await test('confirmed EDIT remains distinct from unknown publication and is reverified after reload without POST replay',async()=>{const {p,c}=await page();try{await p.goto(base+'/admin/workshops/W');await p.getByLabel('Tên',{exact:true}).waitFor();await p.locator('fieldset:not([disabled])').waitFor();await p.getByLabel('Tên',{exact:true}).fill('Saved content');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();const edited=[...remembered.keys()][0];assert.ok(edited);await p.getByRole('button',{name:'Xuất bản',exact:true}).click();await p.getByRole('dialog').waitFor();await p.getByRole('button',{name:'Xác nhận thay đổi',exact:true}).click();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();const history=p.getByRole('region',{name:'Lần lưu nội dung đã xác nhận',exact:true});assert.equal(await history.count(),1);assert.match(await history.innerText(),/Lần lưu nội dung trước đã được máy chủ xác nhận/);
  for(let n=0;n<2;n++){await p.reload();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();await p.getByRole('region',{name:'Lần lưu nội dung đã xác nhận',exact:true}).waitFor();assert.ok(requests.some(r=>r.url==='/api/v1/admin/intents/'+edited&&r.method==='GET'));await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).click();await p.getByText('Chưa xác nhận kết quả. Chỉ đọc đối chiếu, không tự gửi lại thao tác.',{exact:true}).waitFor();assert.equal(await p.locator('fieldset[disabled]').count(),1);assert.equal(await p.getByLabel('Tên',{exact:true}).inputValue(),'Saved content');}
  assert.equal(requests.filter(r=>r.method==='POST').length,2);assert.equal(current.title,'Saved content');assert.equal(current.state,'DRAFT');
 }finally{await p.unrouteAll({behavior:'wait'});await c.close();}});
 await test('newer authoritative read cannot erase UNKNOWN warning for committed EDIT with lost reply',async()=>{const {p,c}=await page();const startPosts=requests.filter(r=>r.method==='POST').length;try{await p.route('**/api/v1/admin/intents',async route=>{const actual=await route.fetch({url:'http://127.0.0.1:'+api.address().port+'/api/v1/admin/intents'});assert.equal(actual.status(),200);assert.equal((await actual.json()).code,'UPDATED');await route.abort('failed');});await p.goto(base+'/admin/workshops/W');await p.locator('fieldset:not([disabled])').waitFor();await p.getByLabel('Tên',{exact:true}).fill('Lost committed EDIT title');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Chưa xác nhận kết quả. Không tự gửi lại thao tác; dùng Kiểm tra kết quả.',{exact:true}).waitFor();await p.getByRole('button',{name:'Tải và đối chiếu',exact:true}).click();await p.getByRole('region',{name:'Dữ liệu mới',exact:true}).waitFor();assert.equal(await p.getByText('Chưa xác nhận kết quả. Không tự gửi lại thao tác; dùng Kiểm tra kết quả.',{exact:true}).count(),1);assert.equal(await p.locator('fieldset[disabled]').count(),1);assert.equal(requests.filter(r=>r.method==='POST').length,startPosts+1);await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();assert.equal(requests.filter(r=>r.method==='POST').length,startPosts+1);}finally{await p.unrouteAll({behavior:'wait'});await c.close();}});
 await test('foreign actor saved-content marker is never rendered or looked up',async()=>{const {p,c}=await page();try{await p.addInitScript(value=>sessionStorage.setItem('workshop-admin-content:A:E:W',JSON.stringify(value)),{...marker,actor:'OTHER',command:{...marker.command,intentId:'FOREIGN-MARKER'}});await p.goto(base+'/admin/workshops/W');await p.locator('fieldset:not([disabled])').waitFor();assert.equal(await p.getByRole('region',{name:'Lần lưu nội dung đã xác nhận',exact:true}).count(),0);assert.equal(requests.filter(r=>r.url.endsWith('/FOREIGN-MARKER')).length,0);}finally{await p.unrouteAll({behavior:'wait'});await c.close();}});
 await test('unavailable historical result cannot be restored as confirmed from local marker alone',async()=>{const {p,c}=await page();try{remembered.set('EDIT-KNOWN',{state:'FINAL',code:'UPDATED',effect:'APPLIED',workshopId:'W'});receiptUnavailable=true;await p.addInitScript(value=>sessionStorage.setItem('workshop-admin-content:A:E:W',JSON.stringify(value)),marker);await p.goto(base+'/admin/workshops/W');await p.locator('fieldset:not([disabled])').waitFor();assert.equal(await p.getByRole('region',{name:'Lần lưu nội dung đã xác nhận',exact:true}).count(),0);}finally{receiptUnavailable=false;await p.unrouteAll({behavior:'wait'});await c.close();}});
}finally{if(browser)await browser.close();child.kill('SIGTERM');const timer=setTimeout(()=>child.kill('SIGKILL'),10000);await closed;clearTimeout(timer);await new Promise(r=>api.close(r));console.log(JSON.stringify({serverStdout:stdout,serverStderr:stderr,scope:'built Web/native Mac Chrome + explicit fake API; no backend integration/acceptance'}));}
