import assert from 'node:assert/strict';import {writeFileSync,readFileSync,existsSync,renameSync} from 'node:fs';
import {SocketClient,until,sleep} from './socket-client.mjs';
export async function checkUpdates({context,base,record,closeExisting}){
 await closeExisting();const raw=[];const evidence={cases:[],measurements:[],sockets:[]};let sequence=0;
 const open=async(options)=>{const s=await SocketClient.open(options);raw.push(s);return s;};
 const closeRaw=async()=>{for(const s of raw)s.close();await until(()=>raw.every(s=>s.closed),'raw close');raw.length=0;await sleep(500);};
 const control=async action=>{const id=++sequence,file='/out/control-request-'+id+'.tmp';writeFileSync(file,JSON.stringify({id,action}));renameSync(file,'/out/control-request.json');await until(()=>{if(existsSync('/out/control-error.txt'))throw Error(readFileSync('/out/control-error.txt','utf8'));if(!existsSync('/out/control-result.json'))return false;const r=JSON.parse(readFileSync('/out/control-result.json'));return r.id===id&&r.status==='DONE';},'owned fixture control '+action,10000);return JSON.parse(readFileSync('/out/control-result.json'));};
 const a=await context('A'),v=await context('V');const api=async(c,route)=>{const r=await c.request.get(base+'/api/v1'+route);assert.equal(r.status(),200);return r.json();};
 const admin=async(body)=>{const r=await a.request.post(base+'/api/v1/admin/intents',{headers:{origin:base,'x-csrf-token':'FAKE-CSRF-A'},data:{epoch:'epoch-t02-fixture',...body}});assert.equal(r.status(),200);return r.json();};
 try{
  const publicCollection=await open(),adminCollection=await open({actor:'FAKE-LAB-A'});publicCollection.subscribe('public','*');adminCollection.subscribe('admin','*','FAKE-CSRF-A');await until(()=>publicCollection.snapshots().length===1&&adminCollection.snapshots().length===1,'authorized collections');
  const created=await admin({intentId:'live-create',action:'CREATE',fields:{title:'Workshop cập nhật trực tiếp',description:'Dữ liệu giả T05; không có thanh toán.',capacity:2,schedule:{start:'2026-10-03T09:00:00+07:00',end:'2026-10-03T10:00:00+07:00'}}});assert.equal(created.code,'CREATED');const id=created.workshopId;
  await until(()=>adminCollection.snapshots().some(ws=>ws.some(w=>w.id===id&&w.state==='DRAFT')),'draft reaches only admin collection');assert.ok(publicCollection.snapshots().every(ws=>ws.every(w=>w.id!==id&&w.state!=='DRAFT')));record('updates-real-collection-creation-DRAFT-admin-only');
  const draft=await open();draft.subscribe('public',id);await until(()=>draft.closed,'public DRAFT denied');assert.equal(draft.snapshots().length,0);record('updates-public-DRAFT-no-snapshot');
  for(const [name,options,audience,csrf,epoch,extra]of [
   ['wrong-origin',{origin:'https://evil.test'},'public','','epoch-t02-fixture',null],
   ['invalid-cookie-no-downgrade',{actor:'REVOKED-UNKNOWN'},'public','','epoch-t02-fixture',null],
   ['wrong-CSRF',{actor:'FAKE-LAB-A'},'admin','WRONG','epoch-t02-fixture',null],
   ['participant-not-admin',{actor:'FAKE-LAB-V'},'admin','FAKE-CSRF-V','epoch-t02-fixture',null],
   ['old-epoch',{actor:'FAKE-LAB-A'},'admin','FAKE-CSRF-A','OLD',null],
   ['URL-credentials',{path:'/api/v1/updates?token=FAKE-LAB-A'},'public','','epoch-t02-fixture',null],
   ['role-forgery',{actor:'FAKE-LAB-V'},'admin','FAKE-CSRF-V','epoch-t02-fixture',{actor:'A',role:'admin'}]
  ]){const s=await open(options);s.send({type:'SUBSCRIBE',audience,epoch,csrf,workshopId:id,...(extra??{})});await until(()=>s.closed,'deny '+name);assert.equal(s.messages.length,0,'no data before denied '+name);evidence.cases.push({name,status:'PASS',messages:s.messages});}
  record('updates-Origin-CSRF-epoch-role-cookie-URL-denied');
  assert.equal((await admin({intentId:'live-publish',action:'STATE',workshopId:id,targetState:'OPEN'})).code,'UPDATED');
  await until(()=>publicCollection.snapshots().some(ws=>ws.some(w=>w.id===id&&w.state==='OPEN')),'published workshop enters public collection');record('updates-real-publish-enters-authorized-public-collection');
  const publicSocket=await open();publicSocket.subscribe('public',id);await until(()=>publicSocket.snapshots().length===1,'public initial');assert.equal(publicSocket.messages[0].message.type,'SUBSCRIBED');assert.equal(publicSocket.messages[1].message.type,'SNAPSHOT');
  const privateSocket=await open({actor:'FAKE-LAB-V'});privateSocket.subscribe('private',null,'FAKE-CSRF-V');await until(()=>privateSocket.snapshots().length===1,'private initial');
  const publicPage=await v.newPage(),adminPage=await a.newPage();const wireEvents=[];
  // Lab-only reference capture: instances still use the native TLS WebSocket.
  await publicPage.addInitScript(()=>{const Native=globalThis.WebSocket;globalThis.__kideaOwnedSockets=[];globalThis.WebSocket=class extends Native{constructor(...args){super(...args);globalThis.__kideaOwnedSockets.push(this);}};});
  publicPage.on('websocket',socket=>socket.on('framesent',({payload})=>{let value;try{value=JSON.parse(String(payload));}catch{return;}if(value.type==='SUBSCRIBE')wireEvents.push({kind:'SUBSCRIBE',audience:value.audience});}));
  publicPage.on('request',r=>{if(r.method()==='GET'){const path=new URL(r.url()).pathname;if(path==='/api/v1/workshops/'+id)wireEvents.push({kind:'GET',audience:'public'});if(path==='/api/v1/me/registrations')wireEvents.push({kind:'GET',audience:'private'});}});let pageWrites=0;for(const p of [publicPage,adminPage])p.on('request',r=>{if(r.method()==='POST')pageWrites++;});await publicPage.goto(base+'/workshops/'+id);await publicPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor();await publicPage.getByText('Đang đối chiếu đăng ký trực tiếp.',{exact:true}).waitFor();await adminPage.goto(base+'/admin/workshops/'+id);await adminPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor();
  const before=Date.now();const register=await v.request.post(base+'/api/v1/registrations',{headers:{origin:base,'x-csrf-token':'FAKE-CSRF-V'},data:{epoch:'epoch-t02-fixture',requestId:'live-register',workshopId:id}});const result=await register.json();assert.equal(result.code,'REGISTERED');
  await publicPage.getByText('1/2 chỗ còn theo lần quan sát.',{exact:true}).waitFor();await publicPage.getByRole('button',{name:'Hủy đăng ký',exact:true}).waitFor();await adminPage.getByText('Đăng ký hiệu lực: 1 · Sức chứa: 2 · Quan sát',{exact:false}).waitFor();await until(()=>publicSocket.snapshots().some(s=>s.active===1),'public changed');await until(()=>privateSocket.snapshots().some(groups=>groups.some(g=>g.workshopId===id&&g.registrations.some(r=>r.id===result.registrationId&&r.state==='ACTIVE'))),'private changed');
  const ms=Date.now()-before;evidence.measurements.push({case:'registration to all three observed UIs and raw channels',milliseconds:ms,limitMilliseconds:5000,injectedFault:false,scope:'single mutation lab; not workload percentile/performance certification'});assert.ok(ms<=5000,'QF_SINGLE_MUTATION_OVER_5s');
  assert.ok(publicSocket.messages.every(e=>!JSON.stringify(e).includes(result.registrationId)&&!JSON.stringify(e).includes('"actor"')));assert.ok(privateSocket.snapshots().every(groups=>groups.every(g=>g.actor==='V')));record('updates-real-public-admin-private-authoritative-version-audience');
  const cancelled=await v.request.post(base+'/api/v1/registrations/'+result.registrationId+'/cancel',{headers:{origin:base,'x-csrf-token':'FAKE-CSRF-V'},data:{epoch:'epoch-t02-fixture',requestId:'live-cancel',workshopId:id}});assert.equal((await cancelled.json()).code,'CANCELLED');await publicPage.getByText(result.registrationId+' · Đã hủy',{exact:true}).waitFor();await publicPage.getByText('2/2 chỗ còn theo lần quan sát.',{exact:true}).waitFor();record('updates-real-CANCELLED-not-resurrected-and-seats-reconciled');
  for(const [page,name]of [[publicPage,'public'],[adminPage,'admin']]){await page.setViewportSize({width:360,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:'/out/updates-'+name+'-360.png',fullPage:true});}record('updates-live-public-admin-360-no-horizontal-overflow');
  // Only these session HTTP replies are injected; WSS and domain replies stay
  // native TLS/backend. A technical rejection must recover by reads, whereas
  // the later real SQL revocation must clear private data and stop the channel.
  for(const status of [429,503]){
   let hits=0;const fault=async route=>{hits++;await route.fulfill({status,contentType:'application/json',body:JSON.stringify({code:status===429?'RATE_LIMIT':'ADMISSION',phase:'UNKNOWN'})});};
   await publicPage.route('**/api/v1/session',fault);await until(()=>hits>=2,'injected participant session fault '+status,6000);
   await publicPage.getByText('Chưa xác nhận cập nhật trực tiếp. Số liệu dưới đây là lần quan sát trước.',{exact:true}).waitFor();await publicPage.getByText('Chưa xác nhận cập nhật đăng ký trực tiếp.',{exact:true}).waitFor();assert.equal(pageWrites,0);
   await publicPage.unroute('**/api/v1/session',fault);await publicPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor({timeout:15000});await publicPage.getByText('Đang đối chiếu đăng ký trực tiếp.',{exact:true}).waitFor({timeout:15000});await publicPage.getByText(result.registrationId+' · Đã hủy',{exact:true}).waitFor();assert.equal(await publicPage.getByText('Chưa kiểm tra được phiên. Chỉ đọc đối chiếu lại, không tự gửi thao tác.',{exact:true}).count(),0);assert.equal(pageWrites,0);
   evidence.cases.push({name:'participant temporary session HTTP '+status+' recovers',status:'PASS',injectedFault:true,faultReplies:hits});
  }
  record('updates-injected-participant-session-429-503-read-recovery-not-revocation-no-POST');
  const title=await adminPage.getByLabel('Tên',{exact:true}).inputValue();await adminPage.getByLabel('Tên',{exact:true}).fill('Phần nhập chưa gửi khi gián đoạn');
  for(const status of [429,503]){
   let hits=0;const fault=async route=>{hits++;await route.fulfill({status,contentType:'application/json',body:JSON.stringify({code:status===429?'RATE_LIMIT':'ADMISSION',phase:'UNKNOWN'})});};
   await adminPage.route('**/api/v1/session',fault);await until(()=>hits>=1,'injected admin session fault '+status,6000);await adminPage.getByRole('heading',{name:'Chưa xác nhận phiên quản trị',exact:true}).waitFor({timeout:6000});assert.equal(await adminPage.getByLabel('Tên',{exact:true}).isVisible(),false);assert.equal(await adminPage.getByLabel('Tên',{exact:true}).inputValue(),'Phần nhập chưa gửi khi gián đoạn');assert.equal(pageWrites,0);
   await adminPage.unroute('**/api/v1/session',fault);await adminPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor({timeout:15000});assert.equal(await adminPage.getByLabel('Tên',{exact:true}).inputValue(),'Phần nhập chưa gửi khi gián đoạn');assert.equal(pageWrites,0);evidence.cases.push({name:'admin temporary session HTTP '+status+' preserves draft and recovers',status:'PASS',injectedFault:true,faultReplies:hits});
  }
  await adminPage.getByLabel('Tên',{exact:true}).fill(title);record('updates-injected-admin-session-429-503-read-recovery-preserves-draft-no-POST');
  await until(()=>publicSocket.snapshots().at(-1)?.active===0,'raw cancellation before no-op');const count=publicSocket.snapshots().length;assert.equal((await admin({intentId:'live-noop',action:'EDIT',workshopId:id,fields:{capacity:2}})).code,'UNCHANGED');await until(()=>publicSocket.messages.some(e=>e.message.type==='HEARTBEAT'),'heartbeat',3500);await sleep(600);assert.equal(publicSocket.snapshots().length,count);record('updates-heartbeat-is-not-domain-event-noop-no-fake-snapshot');
  const pauseReceipt=await control('PAUSE_APP');const pauseAt=Date.parse(pauseReceipt.at);await publicPage.getByText('Chưa xác nhận cập nhật trực tiếp. Số liệu dưới đây là lần quan sát trước.',{exact:true}).waitFor({timeout:6500});const staleMs=Date.now()-pauseAt;assert.ok(staleMs<=6000,'STALE_LOCAL_TIMER_TOO_LATE');assert.equal(await publicPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).count(),0);assert.equal(await publicPage.getByText('2/2 chỗ còn theo lần quan sát.',{exact:true}).count(),1);evidence.measurements.push({case:'actual owned app-container pause to stale UI',milliseconds:staleMs,scope:'>5s stale threshold plus 250ms local timer and measured control roundtrip; retained last observation'});await control('UNPAUSE_APP');await publicPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor({timeout:15000});assert.equal(pageWrites,0);record('updates-real-app-blackout-local-stale-then-valid-signal-no-mutation-replay');
  wireEvents.length=0;await publicPage.evaluate(()=>{for(const socket of globalThis.__kideaOwnedSockets)if(socket.readyState===globalThis.WebSocket.OPEN)socket.close(1000,'Owned lab reconnect case');});
  await publicPage.getByText('Chưa xác nhận cập nhật trực tiếp. Số liệu dưới đây là lần quan sát trước.',{exact:true}).waitFor();await publicPage.getByText('Chưa xác nhận cập nhật đăng ký trực tiếp.',{exact:true}).waitFor();await publicPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor({timeout:15000});await publicPage.getByText('Đang đối chiếu đăng ký trực tiếp.',{exact:true}).waitFor({timeout:15000});for(const audience of ['public','private']){const sub=wireEvents.findIndex(e=>e.kind==='SUBSCRIBE'&&e.audience===audience),get=wireEvents.findIndex(e=>e.kind==='GET'&&e.audience===audience);assert.ok(sub>=0&&get>sub,'REAL_SUBSCRIBE_BEFORE_GET_'+audience);}assert.equal(pageWrites,0);evidence.cases.push({name:'actual native TLS browser sockets closed and reopened',status:'PASS',timeline:wireEvents});record('updates-real-known-close-reconnect-SUBSCRIBE-before-GET-no-POST');
  const ownHistory=await api(v,'/me/registrations');assert.equal(ownHistory.find(g=>g.workshopId===id).registrations.length,1);assert.equal(ownHistory.find(g=>g.workshopId===id).registrations[0].state,'CANCELLED');
  await control('REVOKE_V');await until(()=>privateSocket.closed,'revoked private socket closed',3500);await until(async()=>!(await publicPage.content()).includes(result.registrationId),'revocation hides private DOM',8000);assert.equal(await publicPage.getByRole('link',{name:'Xem đăng ký của tôi',exact:true}).count(),0);for(const name of ['Đăng ký','Hủy đăng ký'])assert.equal(await publicPage.getByRole('button',{name,exact:true}).count(),0);record('updates-real-session-revocation-closes-channel-hides-private-history');
  await adminPage.reload();await adminPage.getByText('Đang đối chiếu cập nhật trực tiếp.',{exact:true}).waitFor();await adminPage.getByLabel('Tên',{exact:true}).waitFor();
  const adminRaw=await open({actor:'FAKE-LAB-A'});adminRaw.subscribe('admin',id,'FAKE-CSRF-A');await until(()=>adminRaw.snapshots().length===1,'admin revocation subscription');await control('REVOKE_A');await until(()=>adminRaw.closed,'revoked admin socket closes',3500);await adminPage.getByRole('heading',{name:'Cần kiểm tra lại phiên quản trị',exact:true}).waitFor({timeout:8000});assert.equal(await adminPage.getByLabel('Tên',{exact:true}).count(),0);await control('RESTORE_A');record('updates-real-admin-revocation-hides-form-without-replaying-intent');
  evidence.sockets.push({name:'public',messages:publicSocket.messages},{name:'private-own-V',messages:privateSocket.messages});await closeRaw();await closeExisting();
  for(const kind of ['unknown-command','invalid-ACK','oversize-frame','fragmented-oversize']){const s=await open({actor:'FAKE-LAB-A'});s.subscribe('admin',id,'FAKE-CSRF-A');await until(()=>s.snapshots().length===1,'frame case start');if(kind==='unknown-command')s.send({type:'MUTATE',action:'DELETE'});else if(kind==='invalid-ACK')s.send({type:'ACK',receipt:'guessed'});else if(kind==='oversize-frame')s.frame('x'.repeat(8193));else{s.frame('x'.repeat(6000),{fin:false,opcode:1});s.frame('x'.repeat(6000),{fin:true,opcode:0});}await until(()=>s.closed,'frame denied '+kind);evidence.cases.push({name:kind,status:'PASS'});}
  record('updates-unknown-commands-guessed-ACK-single-and-fragmented-frame-limit');await closeRaw();
  const burst=await open({actor:'FAKE-LAB-A',autoAck:false});burst.subscribe('admin',id,'FAKE-CSRF-A');await until(()=>burst.snapshots().length===1,'frame rate case');const markers=burst.messages.map(e=>e.receipt);for(let i=0;i<11;i++)burst.send({type:'ACK',receipt:markers[i%2]});await until(()=>burst.closed,'frame burst closes');record('updates-abusive-ACK-flood-closes-not-isolated-rate-proof');await closeRaw();
  const actor=[];for(let i=0;i<8;i++){const s=await open({actor:'FAKE-LAB-SOCK-0'});s.subscribe('public',id,'FAKE-CSRF-SOCK-0');await until(()=>s.snapshots().length===1,'actor slot '+i);actor.push(s);}const ninth=await open({actor:'FAKE-LAB-SOCK-0'});ninth.subscribe('public',id,'FAKE-CSRF-SOCK-0');await until(()=>ninth.closed,'actor ninth denied');assert.equal(ninth.messages.length,0);assert.equal(actor.filter(s=>!s.closed).length,8);record('updates-real-actor-eight-socket-limit');await closeRaw();
  const guests=[];for(let i=0;i<16;i++){const s=await open();s.subscribe('public',id);await until(()=>s.snapshots().length===1,'guest slot '+i);guests.push(s);}const seventeenth=await open();seventeenth.subscribe('public',id);await until(()=>seventeenth.closed,'anonymous seventeenth denied');assert.equal(guests.filter(s=>!s.closed).length,16);record('updates-real-anonymous-sixteen-peer-limit');await closeRaw();
  const all=[];for(let n=0;n<16;n++)for(let i=0;i<8;i++){const s=await open({actor:'FAKE-LAB-SOCK-'+n});s.subscribe('public',id,'FAKE-CSRF-SOCK-'+n);await until(()=>s.snapshots().length===1,'global slot '+n+'/'+i);all.push(s);}const extra=await open({actor:'FAKE-LAB-A'});extra.subscribe('admin',id,'FAKE-CSRF-A');await until(()=>extra.closed,'global 129th denied');assert.equal(all.filter(s=>!s.closed).length,128);record('updates-real-global-128-pending-active-limit');await closeRaw();
  const slow=await open({autoAck:false});slow.subscribe('public',id);await until(()=>slow.closed,'slow reader bounded credit closes',22000);assert.equal(slow.messages.length,8);assert.ok(slow.messages.every(e=>e.message.audience==='public'));record('updates-real-no-ACK-reader-eight-frame-bound-and-close');await closeRaw();
  const finalAdmin=await context('A'),finalAnonymous=await context(null);assert.equal((await api(finalAdmin,'/admin/workshops/'+id)).active,0);assert.equal((await api(finalAnonymous,'/workshops/'+id)).remaining,2);assert.equal(pageWrites,0);record('updates-admission-tests-never-mutated-domain-or-blocked-writer');
 }finally{evidence.unfinishedSockets=raw.map((s,index)=>({index,closed:s.closed,messages:s.messages}));for(const s of raw)s.close();writeFileSync('/out/updates-evidence.json',JSON.stringify(evidence,null,2));}
}
