import test from 'node:test';import assert from 'node:assert/strict';
import {PublicUpdates,decodeUpdate,openUpdates,authoritativeHistoryVersion,reconcileHistory,mergeHistory} from '../../src/lib/updates.ts';
import {ClientState} from '../../src/lib/state.ts';
const snap=(version='1',extra={})=>({id:'W',epoch:'E',version,state:'OPEN',title:'Workshop',description:'Plain text',capacity:10,active:0,remaining:10,observedAt:1,schedule:{start:'2026-10-01T09:00:00+07:00',end:'2026-10-01T10:00:00+07:00'},...extra});
const frame=(type,extra={})=>JSON.stringify({message:{type,epoch:'E',audience:'public',...extra},receipt:'x'.repeat(32)});
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function harness(extra={}){const listeners={},sent=[],statuses=[],reads=[];let closed=false;const wire={state:()=>1,send:v=>sent.push(JSON.parse(v)),close:()=>{closed=true;},listen:(kind,fn)=>{listeners[kind]=fn;}};const stop=openUpdates({audience:'public',epoch:'E',workshopId:'W',csrf:()=>'',validate:async()=>true,read:async()=>{reads.push('GET');return snap();},snapshot:()=>true,status:v=>statuses.push(v),factory:()=>wire,...extra});return {listeners,sent,statuses,reads,stop,closed:()=>closed};}
test('public stream replaces whole snapshots, never applies seat deltas',()=>{const s=new PublicUpdates('E',[snap()]);assert.equal(s.merge(snap('2',{active:1,remaining:9}),'SOCKET'),true);assert.equal(s.merge(snap('1'),'HTTP'),true);assert.equal(s.snapshots.get('W').active,1);assert.equal(s.merge(snap('2',{active:1,remaining:9}),'SOCKET'),true);assert.equal(s.snapshots.get('W').active,1);});
test('public same-version contradiction becomes unknown until explicit HTTP read',()=>{const s=new PublicUpdates('E',[snap()]);assert.equal(s.merge(snap('1',{title:'Wrong'}),'SOCKET'),false);assert.equal(s.snapshots.get('W').title,'Workshop');assert.equal(s.merge(snap(),'SOCKET'),false);assert.equal(s.merge(snap(),'HTTP'),true);assert.equal(s.uncertain.size,0);});
test('uint64 ordering is exact and separate workshops never share a cursor',()=>{const s=new PublicUpdates('E',[snap('9007199254740993')]);s.merge(snap('9007199254740992',{title:'Old'}),'HTTP');s.merge(snap('1',{id:'OTHER',title:'Other'}),'SOCKET');assert.equal(s.snapshots.get('W').title,'Workshop');assert.equal(s.snapshots.size,2);});
test('bad schema, private identity, DRAFT and wrong epoch do not enter public state',()=>{const s=new PublicUpdates('E',[snap()]);for(const v of [snap('1',{state:'DRAFT'}),snap('1',{epoch:'OLD'}),snap('1',{remaining:999}),{actor:'SECRET'}])assert.equal(s.merge(v,'SOCKET'),false);assert.equal(s.snapshots.size,1);});
test('an older collection cannot delete an already observed workshop',()=>{const s=new PublicUpdates('E',[snap(),snap('2',{id:'OTHER'})]);assert.equal(s.merge([],'HTTP'),true);assert.equal(s.snapshots.size,2);});
test('strict envelope matches epoch and audience; malformed frames fail closed',()=>{assert.ok(decodeUpdate(frame('HEARTBEAT'),'E','public'));for(const raw of ['{',frame('SNAPSHOT'),frame('MUTATION'),frame('HEARTBEAT',{epoch:'OLD'}),frame('HEARTBEAT',{audience:'private'})])assert.equal(decodeUpdate(raw,'E','public'),null);});
test('subscribe happens before GET and all further commands are ACK, never POST',async()=>{const h=harness();try{await flush();h.listeners.open();await flush();assert.equal(h.sent[0].type,'SUBSCRIBE');assert.deepEqual(h.reads,[]);h.listeners.message(frame('SUBSCRIBED'));await flush();assert.deepEqual(h.reads,['GET']);assert.equal(h.sent[1].type,'ACK');assert.deepEqual(h.statuses,['UNKNOWN','OBSERVED']);}finally{h.stop();}});
test('known disconnection immediately marks unknown',async()=>{const h=harness({reconnectMs:100000});try{await flush();h.listeners.open();await flush();h.listeners.message(frame('SUBSCRIBED'));await flush();h.listeners.close();assert.equal(h.statuses.at(-1),'UNKNOWN');assert.equal(h.closed(),true);}finally{h.stop();}});
test('a generation closed while GET is pending never applies late data',async()=>{let finish,applied=0;const h=harness({read:()=>new Promise(r=>{finish=r;}),snapshot:()=>{applied++;return true;}});await flush();h.listeners.open();await flush();h.listeners.message(frame('SUBSCRIBED'));await flush();h.stop();finish(snap());await flush();assert.equal(applied,0);assert.equal(h.sent.length,1);});
test('revoked actor before a message cannot render private payload or ACK it',async()=>{let allowed=true,applied=0;const h=harness({validate:async()=>allowed,snapshot:()=>{applied++;return true;},reconnectMs:100000});try{await flush();h.listeners.open();await flush();h.listeners.message(frame('SUBSCRIBED'));await flush();assert.equal(applied,1);allowed=false;h.listeners.message(frame('SNAPSHOT',{data:snap('2')}));await flush();assert.equal(applied,1);assert.equal(h.closed(),true);assert.equal(h.statuses.at(-1),'UNKNOWN');}finally{h.stop();}});
test('bounded client queue rejects a ninth frame while validation is stuck',async()=>{let allowed=true;const h=harness({validate:()=>allowed?Promise.resolve(true):new Promise(()=>{}),reconnectMs:100000});try{await flush();h.listeners.open();await flush();allowed=false;for(let i=0;i<9;i++)h.listeners.message(frame('HEARTBEAT'));await flush();assert.equal(h.closed(),true);}finally{h.stop();}});
test('oversize envelope closes the client without applying data',async()=>{const h=harness({reconnectMs:100000});try{await flush();h.listeners.message('x'.repeat(1048577));assert.equal(h.closed(),true);}finally{h.stop();}});
test('authoritative private GET cannot resurrect history older than its high-water',()=>{assert.equal(authoritativeHistoryVersion('9007199254740993','9007199254740992'),false);assert.equal(authoritativeHistoryVersion('2','2'),true);assert.equal(authoritativeHistoryVersion('2','3'),true);assert.equal(authoritativeHistoryVersion('2',3),false);});

test('private explicit reconciliation resolves equal version while preserving newer CANCELLED',()=>{const client=new ClientState('A','E'),c={...client.context};const group={actor:'A',epoch:'E',workshopId:'W',workshopVersion:'2',registrations:[{id:'R',state:'CANCELLED'}]};client.merge(group,c);client.merge({...group,registrations:[{id:'R',state:'ACTIVE'}]},c);assert.equal(client.uncertain.has('W'),true);assert.equal(reconcileHistory(client,[group],c),true);assert.equal(reconcileHistory(client,[{...group,workshopVersion:'1',registrations:[{id:'R',state:'ACTIVE'}]}],c),true);assert.equal(client.history.get('W').registrations[0].state,'CANCELLED');client.reset('B','E');assert.equal(reconcileHistory(client,[group],c),false);assert.equal(client.history.size,0);});
test('malformed private HTTP batch is rejected before any partial application',()=>{const client=new ClientState('A','E'),c={...client.context};const group={actor:'A',epoch:'E',workshopId:'W',workshopVersion:'1',registrations:[]};assert.equal(reconcileHistory(client,[group,{...group,actor:'B'}],c),false);assert.equal(client.history.size,0);assert.equal(reconcileHistory(client,[group,group],c),false);});

test('buffered heartbeat processing never invents a fresh receive timestamp',async()=>{let stamp=0,finish;const h=harness({now:()=>stamp,read:()=>new Promise(r=>{finish=r;})});try{await flush();h.listeners.open();await flush();h.listeners.message(frame('SUBSCRIBED'));await flush();stamp=6000;finish(snap());await flush();assert.equal(h.statuses.at(-1),'UNKNOWN');h.listeners.message(frame('HEARTBEAT'));await flush();assert.equal(h.statuses.at(-1),'OBSERVED');}finally{h.stop();}});

test('malformed socket collection never partially advances private history',()=>{const client=new ClientState('A','E'),c={...client.context};const group={actor:'A',epoch:'E',workshopId:'W',workshopVersion:'1',registrations:[{id:'R',state:'CANCELLED'}]};assert.equal(mergeHistory(client,[group,{...group,actor:'B'}],c),false);assert.equal(client.history.size,0);assert.equal(mergeHistory(client,[group,group],c),false);assert.equal(mergeHistory(client,[group],c),true);assert.equal(client.history.get('W').registrations[0].state,'CANCELLED');});

test('a contradictory duplicate workshop in one collection is rejected before applying either',()=>{const s=new PublicUpdates('E',[]);assert.equal(s.merge([snap(),snap('1',{title:'Contradiction'})],'SOCKET'),false);assert.equal(s.snapshots.size,0);assert.equal(s.merge([snap(),snap()],'HTTP'),false);assert.equal(s.snapshots.size,0);});
