from pathlib import Path
import json,subprocess,hashlib,uuid
repo=Path('/Users/kendrick/Desktop/kidea');pilot=Path('/Users/kendrick/Desktop/kidea-workshop-pilot');run=Path('/Users/kendrick/Desktop/kidea-t02-build-lab/t02-be72d72c-9405-4dfa-88d3-ddfe608d5330');assert json.loads((run/'results.json').read_text())['state']=='EVIDENCE_READY_WITH_TSAN_LIMITATION_REVIEW_REQUIRED'
e=repo/'tests/evidence/r09/t04-query-plan-r2';e.mkdir(exist_ok=False);scratch=repo/'.test-output/t04-query-plan-r2';scratch.mkdir(exist_ok=False);scratch.chmod(0o777);vendor=(pilot/json.loads((pilot/'containers/t02/vendor-lock.json').read_text())['root']).resolve();build=run/'dev/build/dev';source=repo/'tests/r09/t04/query-plan.c';schema=pilot/'backend/schema/001.sql';image='sha256:6fba0f63f498882a30a8dce7a1d7b6fa051d44b113f3188c38977f7a20e65a92';name='r09-quota-plan-'+uuid.uuid4().hex
files=[source,schema,build/'libworkshop_sqlite.a',vendor/'sqlite/sqlite3.h'];hashes={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files};args=['docker','run','--rm','--pull=never','--name',name,'--network=none','--read-only','--user','1000:1000','--cpus=1','--memory=1g','--memory-swap=1g','--pids-limit=64','--cap-drop=ALL','--security-opt=no-new-privileges','--tmpfs','/tmp:rw,nosuid,size=67108864']
for src,dst in [(source.parent,'/plan'),(schema,'/schema.sql'),(build/'libworkshop_sqlite.a','/libsqlite.a'),(vendor/'sqlite','/sqlite')]:args+=['--mount',f'type=bind,src={src},dst={dst},readonly']
args += ['--mount',f'type=bind,src={scratch},dst=/out']
args += [image,'timeout','--kill-after=5','50','sh','-c','gcc-13 -Wall -Wextra -Werror -I/sqlite /plan/query-plan.c /libsqlite.a -lstdc++ -ldl -lpthread -lm -o /out/query-plan && /out/query-plan /schema.sql']
(e/'manifest.json').write_text(json.dumps({'args':args,'hashes':hashes,'scope':'SQLite query plan against actual unchanged schema and pinned compiled SQLite library'},indent=2)+'\n');v=subprocess.run(args,capture_output=True,text=True,timeout=60);(e/'stdout.txt').write_text(v.stdout);(e/'stderr.txt').write_text(v.stderr);(e/'process.json').write_text(json.dumps({'exit':v.returncode},indent=2)+'\n');assert v.returncode==0,v.stderr;assert 'SQLite 3.53.4' in v.stdout and 'one_active' in v.stdout and 'actor=?' in v.stdout,v.stdout;assert all(hashlib.sha256(Path(p).read_bytes()).hexdigest()==h for p,h in hashes.items());print(v.stdout)
