from pathlib import Path
import json,subprocess
repo=Path('/Users/kendrick/Desktop/kidea');pilot=Path('/Users/kendrick/Desktop/kidea-workshop-pilot').resolve();out=repo/'tests/evidence/r09/t04-continuation-r1';out.mkdir(exist_ok=False)
node='/Users/kendrick/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node';cli=str(repo/'.agents/skills/kidea/scripts/kidea.mjs');refs=[{'path':p,'anchor':None} for p in ['docs/t04/report-r1.md','docs/t04/evidence/index.json','docs/architecture/traceability.md']]
def call(q,label):
 (out/(label+'-request.json')).write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n');v=subprocess.run([node,cli,'resume'],cwd=pilot,input=json.dumps(q),text=True,capture_output=True);(out/(label+'-result.json')).write_text(v.stdout);(out/(label+'-stderr.log')).write_text(v.stderr);d=json.loads(v.stdout);assert v.returncode==0,d;return d
q={'operation':'READ','permission':{'root':str(pilot),'readProject':True,'allowReadLocalGit':True},'requiredFiles':refs};r=call(q,'read');c=r['context'];assert r['state'] in ['CONTEXT_READY','WAITING']
q.update(operation='SAVE',expectedBasis=r['basis'],expectedProjectId=c['projectId'],expectedGit=c['checkout'],checkpoint={'itemId':c['currentItem']['id'],'completed':'T04 final implementation regression and ten semantic impact assessments recorded; R09-T04-OUTPUT-r1 prepared IN_REVIEW, no Human approval invented. Raw failures preserved.','remaining':'Actual Human output review, public CLOSE and return to W-009-MAX2; then T05 admin/events/ops and remaining full-product G2, readiness/Human PROD and R09 scenarios.','nextAction':'Read exact presented R09-T04-OUTPUT-r1 revision 1 digest from Kidea t04-output-review-r1 evidence. Record only actual Human feedback/approval via public approve; CLOSE only after gates verify, then continue unfinished MVP under full R09 execution grant.','sourceRefs':refs})
q['permission'].update(allowSaveContinuation=True,statement='User asked to continue full R09. Save actual bounded T04 completion and retained Human output gate without advancing or approving work.',assumptions={'localFilesystem':True,'noActiveSync':True,'singleKideaRun':True})
r=call(q,'save');assert r['state']=='CONTINUATION_SAVED',r;print(r['state'])
