import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {readMapSources,mapResult,traceabilityMap,reverseTrace} from '../../../.agents/skills/kidea/scripts/maps.mjs';
const root='/Users/kendrick/Desktop/kidea-workshop-pilot',dir=process.argv[2],clang=process.argv[3],ref=(path,anchor=null)=>({path,anchor});
const maps=[JSON.parse(fs.readFileSync(dir+'/web.json')),...['model','store','executor','main'].map(n=>JSON.parse(fs.readFileSync(clang+'/'+n+'-map.json')))];
const extra=['backend/tests/tests.cpp','backend/schema/001.sql','contracts/openapi.json'];const files=[...new Set([...maps.flatMap(m=>m.sources.map(s=>s.path)),...extra])];const input=readMapSources(root,files);const nodes=[...new Map([...maps.flatMap(m=>m.nodes),...extra.map(p=>({id:p,path:p,kind:'file'}))].map(n=>[n.id,n])).values()];
const edges=[...new Map(maps.flatMap(m=>m.edges).map(e=>[JSON.stringify(e),e])).values()];const diagnostics=[...maps.flatMap(m=>m.diagnostics),{code:'FILE_LEVEL_TEST_SCHEMA_CONTRACT',detail:'These files are inventoried, not assigned fabricated compiler calls.'},{code:'CPP_OUT_OF_LINE_OWNER_REQUIRES_REVIEW',detail:'Use actual file targets for Store methods; declaration/definition qualified names require disambiguation before complete symbol-map claims.'}];
const implementation=mapResult(input,{name:'composed-clang-web-and-file-inventory',version:1},{componentDigests:maps.map(m=>m.digest)},nodes,edges,diagnostics,['No unresolved relation was dropped; file inventory adds no inferred calls.']);
const old=fs.readFileSync('tests/evidence/r09/pilot-maps-r2/traceability-draft.md','utf8');const rows=JSON.parse(old.split('```json\n')[1].split('\n```')[0]);rows[0].conditions='Client contract, Mac Chrome and real HTTPS integration have scoped receipts. Backend commit atomicity is separately tested; this is not whole-product acceptance.';
const spec=ref('docs/t04/max2.md');
rows.push(
 {id:'T04-ATOMIC-QUOTA',spec,targets:['backend/src/store.cpp','backend/tests/tests.cpp'],purpose:'Count actor ACTIVE globally inside BEGIN IMMEDIATE before capacity; duplicate and remembered intent keep their earlier priority.',conditions:'Q01 and Q04 compare real final codes/counts/outbox, including two concurrent different-workshop writes. Full original oracle remains required.',evidence:[ref('backend/src/store.cpp'),ref('backend/tests/tests.cpp'),ref('docs/t04/oracle-extension.json')]},
 {id:'T04-LEGACY-CANCEL',spec,targets:['backend/src/store.cpp','backend/schema/001.sql','backend/tests/tests.cpp'],purpose:'Preserve preexisting excess rows; cancellation releases quota once and CANCELLED is excluded. Existing one_active partial index supports actor filtering.',conditions:'Q01/Q02/Q03 assert exact history/count/event consequences and both serial orders; schema/data are not rewritten.',evidence:[ref('backend/src/store.cpp'),ref('backend/schema/001.sql'),ref('backend/tests/tests.cpp')]},
 {id:'T04-HISTORICAL-RESULT',spec,targets:['backend/src/store.cpp','web/src/lib/reply.ts','web/src/lib/Registration.svelte','web/tests/unit/state.test.mjs','backend/tests/tests.cpp'],purpose:'LIMIT_REACHED remains immutable for the same intent after cancellation; fresh intent is a separate server decision. Web does not infer current quota from history.',conditions:'Q01/Q03 and Web tests distinguish old rejection, new success and invalid CANCEL decoding; lost reply/no replay regressions remain.',evidence:[ref('backend/src/store.cpp'),ref('web/src/lib/reply.ts'),ref('web/src/lib/Registration.svelte'),ref('web/tests/unit/state.test.mjs'),ref('backend/tests/tests.cpp')]},
 {id:'T04-CONTRACT',spec,targets:['contracts/openapi.json','web/src/lib/reply.ts','backend/src/store.cpp'],purpose:'Add the REJECTED outcome without claiming a technical failure or granting client-side mutation authority.',conditions:'Old client unknown-code behavior remains uncertain rather than false success; mixed-version release readiness is still an explicit T08 obligation.',evidence:[ref('contracts/openapi.json'),ref('web/src/lib/reply.ts'),ref('backend/src/store.cpp')]}
);
const docs=JSON.parse(fs.readFileSync(dir+'/documentation.json'));const all=[...new Set([...files,...docs.sources.map(s=>s.path),'docs/t04/oracle-extension.json'])];const trace=traceabilityMap(readMapSources(root,all),implementation,rows,{codeRequired:true});assert.equal(rows.length,10);
for(const [name,value]of Object.entries({implementation,traceability:trace,'reverse-store':reverseTrace(trace,'backend/src/store.cpp')}))fs.writeFileSync(dir+'/'+name+'.json',JSON.stringify(value,null,2)+'\n',{flag:'wx'});
const text='# Responsibility mapping — current scoped implementation\n\nSingle authored mapping; reverse lookup is derived. Backend/Web/T04 coverage does not complete admin/events/ops or T14. Compiler/Web diagnostics and unfinished event wiring remain explicit; no fourth progress map.\n\n```json\n'+JSON.stringify(rows,null,2)+'\n```\n';
fs.mkdirSync(root+'/docs/architecture',{recursive:true});fs.writeFileSync(root+'/docs/architecture/traceability.md',text,{flag:'wx'});fs.writeFileSync(dir+'/traceability-authored.md',text,{flag:'wx'});console.log(JSON.stringify({rows:rows.length,edges:trace.edges.length,diagnostics:trace.diagnostics,completeness:trace.completeness}));
