import assert from 'node:assert/strict';
export async function checkAdmin({context,base,record}){
 const a=await context('A');const p=await a.newPage();const writes=[];let lostCreate=true,created;
 await p.route('**/api/v1/admin/intents',async route=>{if(route.request().method()!=='POST')return route.continue();const body=route.request().postDataJSON();writes.push(body);if(lostCreate){lostCreate=false;const actual=await route.fetch();assert.equal(actual.status(),200);created=await actual.json();assert.equal(created.code,'CREATED');await route.abort('failed');return;}await route.continue();});
 await p.goto(base+'/admin/workshops/new');await p.getByLabel('Tên',{exact:true}).waitFor();await p.getByLabel('Tên',{exact:true}).fill('Workshop quản trị T05');await p.getByLabel('Mô tả văn bản thuần').fill('Dữ liệu giả kiểm tạo và sửa.');await p.getByLabel('Sức chứa',{exact:true}).fill('10');await p.getByLabel('Bắt đầu, kèm múi giờ').fill('2026-10-02T09:00:00+07:00');await p.getByLabel('Kết thúc, kèm múi giờ').fill('2026-10-02T10:00:00+07:00');
 await p.getByRole('button',{name:'Tạo bản nháp',exact:true}).click();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();assert.equal(writes.length,1);await p.reload();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();assert.equal(writes.length,1);await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).click();const link=p.getByRole('link',{name:'Mở bản nháp vừa tạo',exact:true});await link.waitFor();assert.equal(new URL(await link.getAttribute('href'),base).pathname,'/admin/workshops/'+created.workshopId);assert.equal(writes.length,1);record('admin-create-real-commit-loss-reload-GET-only-exact-ID');
 const id=created.workshopId;const read=async()=>{const r=await a.request.get(base+'/api/v1/admin/workshops/'+id);assert.equal(r.status(),200);return r.json();};const edit=async(fields,label)=>{const r=await a.request.post(base+'/api/v1/admin/intents',{headers:{origin:base,'x-csrf-token':'FAKE-CSRF-A'},data:{epoch:'epoch-t02-fixture',intentId:'external-'+label,action:'EDIT',workshopId:id,fields}});assert.equal((await r.json()).code,'UPDATED');};
 assert.equal((await read()).state,'DRAFT');const anonymous=await context(null,{javaScriptEnabled:false}),anon=await anonymous.newPage();assert.equal((await anon.goto(base+'/workshops/'+id)).status(),404);assert.ok(!(await anon.content()).includes('Workshop quản trị T05'));assert.equal((await anon.goto(base+'/admin/workshops/'+id)).status(),401);record('admin-draft-never-public-or-anonymous-SSR');await anonymous.close();
 await link.click();await p.waitForURL(base+'/admin/workshops/'+id);await p.getByRole('heading',{name:'Sửa workshop',exact:true}).waitFor();await p.getByLabel('Tên',{exact:true}).waitFor();await p.getByLabel('Tên',{exact:true}).fill('Tên đã sửa');await p.locator('button:disabled').filter({hasText:/^Xuất bản$/}).waitFor();assert.equal(await p.getByRole('button',{name:'Xuất bản',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();assert.deepEqual(writes.at(-1).fields,{title:'Tên đã sửa'});assert.equal(writes.at(-1).action,'EDIT');assert.equal((await read()).state,'DRAFT');record('admin-dirty-only-patch-no-implicit-publish');
 await p.getByRole('button',{name:'Xuất bản',exact:true}).click();await p.getByRole('dialog').waitFor();const before=writes.length;await p.keyboard.press('Escape');assert.equal(writes.length,before);await p.getByRole('button',{name:'Xuất bản',exact:true}).click();await p.getByRole('button',{name:'Xác nhận thay đổi',exact:true}).click();await p.getByRole('button',{name:'Tạm dừng',exact:true}).waitFor();assert.equal((await read()).state,'OPEN');assert.equal(writes.length,before+1);record('admin-state-separate-confirm-Escape-no-write');
 await p.getByLabel('Sức chứa',{exact:true}).fill('9');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByRole('dialog').waitFor();assert.match(await p.getByRole('dialog').innerText(),/10 → 9/);const count=writes.length;await edit({capacity:8},'capacity');
 // Either the background read invalidates the dialog, or the explicit final
 // read does. Neither route may submit the previously confirmed command.
 await p.evaluate(()=>{const dialog=document.querySelector('dialog[open]');const button=dialog&&[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Xác nhận thay đổi');if(button&&!button.disabled)button.click();});await p.getByRole('region',{name:'Dữ liệu mới'}).waitFor();assert.equal(writes.length,count);assert.equal((await read()).capacity,8);assert.equal(await p.getByLabel('Sức chứa',{exact:true}).inputValue(),'9');await p.getByRole('button',{name:'Đã xem bản mới, giữ các trường tôi sửa',exact:true}).click();await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();assert.deepEqual(writes.at(-1).fields,{capacity:9});record('admin-changed-observation-invalidates-sensitive-confirmation');
 await p.getByLabel('Tên',{exact:true}).fill('Tên của tôi');await edit({description:'Nội dung từ người sửa khác'},'description');await p.getByRole('button',{name:'Tải và đối chiếu',exact:true}).click();await p.getByRole('region',{name:'Dữ liệu mới'}).waitFor();assert.equal(await p.getByLabel('Tên',{exact:true}).inputValue(),'Tên của tôi');await p.getByRole('button',{name:'Đã xem bản mới, giữ các trường tôi sửa',exact:true}).click();assert.equal(await p.getByLabel('Mô tả văn bản thuần').inputValue(),'Nội dung từ người sửa khác');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();assert.deepEqual(writes.at(-1).fields,{title:'Tên của tôi'});assert.equal((await read()).description,'Nội dung từ người sửa khác');record('admin-reviewed-rebase-preserves-other-editors-fields');
 const conflictWrites=writes.length;const conflictRoute=base+'/api/v1/admin/workshops/'+id;await p.route(conflictRoute,async route=>{const response=await route.fetch();const body=await response.json();await route.fulfill({response,json:{...body,title:'Contradictory same-version response'}});});await p.getByRole('button',{name:'Tải và đối chiếu',exact:true}).click();await p.getByText('Cùng phiên bản nhưng nội dung khác nhau. Chưa xác nhận dữ liệu; hãy tải và đối chiếu trước khi lưu.',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Lưu nội dung',exact:true}).isDisabled(),true);assert.equal(await p.getByRole('button',{name:'Tạm dừng',exact:true}).isDisabled(),true);assert.equal(await p.getByLabel('Tên',{exact:true}).inputValue(),'Tên của tôi');assert.equal(writes.length,conflictWrites);await p.unroute(conflictRoute);await p.getByRole('button',{name:'Tải và đối chiếu',exact:true}).click();await p.locator('button:not([disabled])').filter({hasText:/^Lưu nội dung$/}).waitFor();assert.equal(writes.length,conflictWrites);record('admin-same-version-conflict-blocks-writes-until-authoritative-reconcile');
 const beforeInvalid=writes.length;await p.getByLabel('Sức chứa',{exact:true}).fill('1.5');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByText('Sức chứa cần là số nguyên từ 1 đến 1.000.',{exact:true}).waitFor();assert.equal(writes.length,beforeInvalid);await p.getByRole('button',{name:'Bỏ phần chưa lưu',exact:true}).click();record('admin-invalid-field-preserves-input-without-POST');
 await p.setViewportSize({width:360,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.screenshot({path:'/out/admin-360.png',fullPage:true});record('admin-responsive-360-no-horizontal-overflow');
 // An actual committed edit loses its reply while the cookie changes to a
 // participant. The old admin result must not render in the new session.
 await p.unroute('**/api/v1/admin/intents');let lastIntent;await p.route('**/api/v1/admin/intents',async route=>{lastIntent=route.request().postDataJSON();const actual=await route.fetch();assert.equal((await actual.json()).code,'UPDATED');await a.addCookies([{name:'workshop_session',value:'FAKE-LAB-V',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);await route.abort('failed');});
 await p.getByLabel('Tên',{exact:true}).fill('Kết quả riêng sau đổi phiên');await p.getByRole('button',{name:'Lưu nội dung',exact:true}).click();await p.getByRole('heading',{name:'Cần kiểm tra lại phiên quản trị',exact:true}).waitFor();assert.ok(!(await p.content()).includes('Kết quả riêng sau đổi phiên'));const denied=await a.request.get(base+'/api/v1/admin/intents/'+lastIntent.intentId);assert.equal(denied.status(),404);record('admin-actor-switch-hides-form-and-denies-old-result');
 await a.addCookies([{name:'workshop_session',value:'FAKE-LAB-A',domain:'workshop.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);await p.unroute('**/api/v1/admin/intents');let replay=0;p.on('request',r=>{if(r.method()==='POST')replay++;});await p.reload();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).waitFor();await p.getByRole('button',{name:'Kiểm tra kết quả',exact:true}).click();await p.getByText('Lần đó đã lưu thay đổi.',{exact:true}).waitFor();assert.equal(replay,0);assert.equal((await read()).title,'Kết quả riêng sau đổi phiên');record('admin-original-actor-restores-intent-through-GET-without-replay');
 await a.close();
}
