import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {digest,verifyPackage,preflight,classify,retryDecision,freshHeartbeat} from './lab-r2/guard.mjs';
import {containerArgs} from './lab-r2/deploy.mjs';
const manifest={revision:'r08-lab-r2.1',digest:'fixed'};
const grant={manifestSHA256:'fixed',targets:['lab-dev'],realProduction:false};
const base={target:'lab-dev',grant,manifest,revision:manifest.revision,attempt:'new-attempt'};
test('authority rejects real/ambiguous target, wrong grant and production privilege',()=>{for(const change of [{target:'production'},{target:''},{target:'lab-prod'},{grant:{...grant,realProduction:true}}])assert.throws(()=>preflight({...base,...change}));assert.doesNotThrow(()=>preflight(base));});
test('revision, approval, retry ID, overlap and source changes cannot pass preflight',()=>{for(const change of [{revision:'r0'},{grant:{...grant,manifestSHA256:'other'}},{attempts:['new-attempt']},{attempt:'../escape'},{busy:true},{sourceValid:false}])assert.throws(()=>preflight({...base,...change}));});
test('package closure detects added file, child edits, removed file and symlink substitution',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'r08-guard-'));try {const file=path.join(dir,'child.mjs');fs.writeFileSync(file,'original');const m={revision:manifest.revision,profile:'release-protocol-fixture',files:{'child.mjs':digest('original')}};verifyPackage(dir,m);fs.writeFileSync(path.join(dir,'extra'),'x');assert.throws(()=>verifyPackage(dir,m));fs.unlinkSync(path.join(dir,'extra'));fs.writeFileSync(file,'changed');assert.throws(()=>verifyPackage(dir,m));fs.unlinkSync(file);assert.throws(()=>verifyPackage(dir,m));fs.symlinkSync('/dev/null',file);assert.throws(()=>verifyPackage(dir,m));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('receipt is insufficient: every artifact/config/schema/target and Web status matters',()=>{const b={target:'lab-dev',artifact:'b',config:'c',schema:1};const w={status:200,artifact:'w'};const e={target:'lab-dev',backend:'b',config:'c',web:'w'};assert.equal(classify(b,w,e),'VERIFIED');for(const change of [{target:'lab-prod'},{artifact:'wrong'},{config:'wrong'},{schema:2}])assert.notEqual(classify({...b,...change},w,e),'VERIFIED');assert.notEqual(classify(b,{...w,artifact:'old'},e),'VERIFIED');assert.notEqual(classify(b,{...w,status:503},e),'VERIFIED');assert.equal(classify(b,null,e),'UNKNOWN');});
test('unknown migration cannot authorize replay; committed migration explicitly blocks replay',()=>{assert.equal(retryDecision(null),'REQUIRES_STATE_RECONCILIATION');assert.equal(retryDecision({migrations:[{id:'fixture-schema-2'}]}),'DO_NOT_REPLAY');});
test('absent, stale and future heartbeat cannot establish health',()=>{for(const value of [null,{at:0},{at:5001}])assert.equal(freshHeartbeat(value,5000),false);assert.equal(freshHeartbeat({at:4500},5000),true);});
test('both lab targets use bounded offline unprivileged container command with no ports/socket',()=>{for(const target of ['lab-dev','lab-prod']){const a=containerArgs({name:'kidea-r08-test',run:'test',target,web:'web-a',fault:'none',image:'sha256:fixed',source:'/snapshot',data:'/data'});for(const x of ['--pull=never','--network=none','--cpus=1','--memory=512m','--read-only','--user=1000:1000','--cap-drop=ALL'])assert.ok(a.includes(x));assert.ok(!a.includes('-p'));assert.ok(!a.some(x=>x.includes('docker.sock')));}assert.throws(()=>containerArgs({name:'kidea-r08-test',target:'production'}));});

test('migration commits data/schema once; replay rolls back without further damage',async()=>{const {DatabaseSync}=await import('node:sqlite');const {migrate}=await import('./lab-r2/migration.mjs');const db=new DatabaseSync(':memory:');try{db.exec("CREATE TABLE metadata(schema_version INTEGER); INSERT INTO metadata VALUES(1); CREATE TABLE records(id INTEGER PRIMARY KEY,value TEXT,role TEXT); INSERT INTO records VALUES(1,'fixture-original','admin'); CREATE TABLE migrations(id TEXT PRIMARY KEY)");migrate(db);assert.equal(db.prepare('SELECT schema_version FROM metadata').get().schema_version,2);assert.equal(db.prepare('SELECT role FROM records').get().role,'reader');assert.throws(()=>migrate(db));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM migrations').get().n,1);assert.equal(db.prepare('SELECT value FROM records').get().value,'fixture-migrated');}finally{db.close();}});
