org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.builder.sdkDownload=false
android.onlyEnableUnitTestForTheTestedBuildType=false
org.gradle.caching=false
kotlin.incremental=false
